Repository eth-cscs/production, pull requests merged in 2018-10, with the labels that each got.

#859 [kesch] Update MCH-RH7.3-17.02
  jenkins-builds/MCH-RH7.3-17.02
Labels: enhancement

#860 [dom-gpu] QuantumESPRESSO 6.3 and libxc with CrayIntel
  easybuild/easyconfigs/l/libxc/libxc-4.2.3-CrayIntel-18.08.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-CrayIntel-18.08.eb
Labels: enhancement

#871 [dom-gpu] Adjusting EASYBUILD_BUILDPATH
  easybuild/module/Easybuild
Labels: bug

#874 [dom-gpu] Adding LAMMPS and QuantumESPRESSO in production list 18.08
  jenkins-builds/6.0.UP07-18.08-gpu
  jenkins-builds/6.0.UP07-18.08-mc
Labels: enhancement

#876 [dom-gpu] Changing EasyBuild modulefile
  easybuild/module/EasyBuild-custom/cscs
  jenkins-builds/6.0.UP07-18.08-gpu
  jenkins-builds/6.0.UP07-18.08-mc
  jenkins-builds/daint-gpu
  jenkins-builds/daint-mc
  jenkins-builds/production.sh
Labels: enhancement

#881 [daint] Updating paths in groovy file and login folder in production
  jenkins/Machines.groovy
  login/daint-gpu
  login/daint-mc
Labels: bug

#882 [daint-mc] Add netcdf-python in daint-mc
  jenkins-builds/6.0.UP07-18.08-mc
Labels: bug

#884 [kesch] GREASY on Kesch
  easybuild/easyconfigs/g/GREASY/GREASY-2.1-cscs-gmvolf-17.02.eb
Labels: enhancement

#886 [daint-gpu] Updating login modules for Piz Daint
  login/daint-gpu
  login/daint-mc
Labels: bug

#888 [daint-gpu] Update xalt section in production
  jenkins-builds/production.sh
Labels: bug

#891 [daint-gpu] Changing Lmod module load command
  jenkins-builds/production.sh
Labels: bug

#894 [daint-gpu] CP2K with perftools and without craype-accel-nvidia60
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-cuda-9.1-pat-7.0.2.eb
Labels: bug

#893 [daint-gpu dom-gpu] reverting magma and CP2K to use only cudatoolkit
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-cuda-9.1.eb
  easybuild/easyconfigs/m/magma/magma-2.2.0-CrayGNU-18.08-cuda-9.1.eb
Labels: bug

#900 [daint dom fulen kesch] Fix bug in 'getMachineConfiguration' method
  jenkins/JenkinsfileRegressionEB
  jenkins/util.groovy
Labels: bug

#899 Add support for jenscscs
  easybuild/module/EasyBuild-custom/cscs
Labels: bug, enhancement
