Repository eth-cscs/production, pull requests merged in 2018-06, with the labels that each got.

#622 [dom daint kesch monch] Bugfix/jenkins production pipeline
  jenkins/JenkinsfileProductionEB
Labels: enhancement

#609 [leone] yade rebuild
  easybuild/easyconfigs/h/h-yade/h-yade-2017.01a-foss-2016b-Python-2.7.12.eb
Labels: enhancement

#621 [daint] Updating cray-python dependency of h5py
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-parallel.eb
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-serial.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6-CrayGNU-17.08.eb
Labels: bug

#631 [daint dom kesch monch leone] Update JenkinsfileProductionEB
  jenkins/JenkinsfileProductionEB
Labels: enhancement

#634 [daint dom kesch leone monch] Update JenkinsfileProductionEB
  jenkins/JenkinsfileProductionEB
Labels: enhancement

#632 [dom-gpu] h5py
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-parallel.eb
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-serial.eb
Labels: bug

#627 [daint] ABCpy version 0.5
  easybuild/easyconfigs/a/abcpy/abcpy-0.5.0-CrayGNU-17.12-python3.eb
  easybuild/easyconfigs/c/cloudpickle/cloudpickle-0.3.1-CrayGNU-17.12-python3.eb
  easybuild/easyconfigs/g/glmnet/glmnet-2.0.0-CrayGNU-17.12-python3.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.18.2-CrayGNU-17.12-python3.eb
  jenkins-builds/6.0.UP04-17.08-gpu
  jenkins-builds/6.0.UP04-17.08-mc
Labels: bug

#635 [dom daint kesch monch leone] Bugfix/jenkins production failure
  jenkins/JenkinsfileProductionEB
Labels: bug

#637 [daint dom] new h5py version in production
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python2-parallel.eb
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python2-serial.eb
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-parallel.eb
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-serial.eb
  jenkins-builds/6.0.UP04-17.08-gpu
  jenkins-builds/6.0.UP04-17.08-mc
Labels: enhancement

#623 [daint-gpu] Updating version of cray-python for Theano-0.9.0
  easybuild/easyconfigs/n/nose-parameterized/nose-parameterized-0.5.0-CrayGNU-17.08-python2.eb
  easybuild/easyconfigs/n/nose-parameterized/nose-parameterized-0.5.0-CrayGNU-17.08-python3.eb
  easybuild/easyconfigs/p/pycuda/pycuda-2017.1.1-CrayGNU-17.08-python2-cuda-8.0.eb
  easybuild/easyconfigs/p/pycuda/pycuda-2017.1.1-CrayGNU-17.08-python3-cuda-8.0.eb
  easybuild/easyconfigs/t/Theano/Theano-0.9.0-CrayGNU-17.08-cuda-8.0-python2.eb
  easybuild/easyconfigs/t/Theano/Theano-0.9.0-CrayGNU-17.08-cuda-8.0-python3.eb
Labels: bug

#633 [daint dom] Updating PyExtensions
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.13.1-CrayGNU-17.08.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6.1.1-CrayGNU-17.08.eb
  jenkins-builds/6.0.UP04-17.08-gpu
  jenkins-builds/6.0.UP04-17.08-mc
Labels: enhancement

#639 [dom daint kesch leone monch] Use also the buildID for the prefix path
  jenkins/JenkinsfileTestingEB
Labels: bug

#629 [daint-gpu] ParaView 5.5.1 fixes a bug with the Ghost Cell Generator
  easybuild/easyconfigs/p/ParaView/ParaView-5.5.1-EGL-CrayGNU-17.08.eb
Labels: enhancement

#646 [daint dom] Remove abcpy-0.3.0 from production lists
  jenkins-builds/6.0.UP04-17.08-gpu
  jenkins-builds/6.0.UP04-17.08-mc
Labels: bug

#643 [daint dom] Boost with cray-python/2.7.13.1 and cray-python/3.6.1.1
  easybuild/easyconfigs/b/Boost/Boost-1.65.0-CrayGNU-17.08-python2.eb
  easybuild/easyconfigs/b/Boost/Boost-1.65.0-CrayGNU-17.08-python3.eb
Labels: bug

#652 [daint] Added pygelf in order to allow grafana logging
  easybuild/easyconfigs/p/Python-bare/Python-bare-3.6.5.eb
Labels: enhancement, ready_to_be_merged

#651 [daint,dom] Add HPX and jemalloc to production lists
  easybuild/easybuild.d/system_wide.cfg
  jenkins-builds/6.0.UP04-17.08-gpu
  jenkins-builds/6.0.UP04-17.08-mc
Labels: ready_to_be_merged

#654 [daint dom kesch monch leone] ReFrame 2.13 easyconfig file
  easybuild/easyconfigs/r/reframe/reframe-2.13.eb
  jenkins-builds/MCH-RH7.3-17.02
  jenkins-builds/common-SLES12-2016.10
  jenkins-builds/leone-RHEL6.7EUS-17.06
  jenkins-builds/monch-RH6.9-17.06
Labels: ready_to_be_merged
