Repository eth-cscs/production, pull requests merged in 2018-11, with the labels that each got.

#911 [dom-gpu] Disable fulen
  jenkins/Machines.groovy
Labels: bug

#916 [daint] Add CMake 3.12.4
  easybuild/easyconfigs/c/CMake/CMake-3.12.4.eb
Labels: bug

#923 [daint-mc] Update LAMMPS-22Aug2018-CrayGNU-18.08.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08.eb
Labels: enhancement

#922 [daint-gpu] LAMMPS-22Aug2018-CrayGNU-18.08-cuda-9.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08-cuda-9.1.eb
Labels: enhancement

#925 Revert "[daint-gpu] LAMMPS-22Aug2018-CrayGNU-18.08-cuda-9.1.eb"
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08-cuda-9.1.eb
Labels: bug

#924 Revert "[daint-mc] Update LAMMPS-22Aug2018-CrayGNU-18.08.eb"
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08.eb
Labels: bug

#707 [fulen] Add Python 2.7.15 gmvolf-18.05
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-gmvolf-18.05.eb
  easybuild/easyconfigs/f/freetype/freetype-2.8.1-gmvolf-18.05.eb
  easybuild/easyconfigs/g/GMP/GMP-6.1.2-gmvolf-18.05.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.34-gmvolf-18.05.eb
  easybuild/easyconfigs/l/libreadline/libreadline-7.0-gmvolf-18.05.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-gmvolf-18.05.eb
  easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-2.2-GCC-8.1.0-2.30.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-gmvolf-18.05.eb
  easybuild/easyconfigs/p/Python/Python-2.7.15-gmvolf-18.05.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.9.2-gmvolf-18.05.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.7-gmvolf-18.05.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.7-gmvolf-18.05-no-X11.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.7_different-prefix-with-tcl.patch
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-gmvolf-18.05.eb
  jenkins-builds/fulen-RH7.4-18.05
  jenkins/Machines.groovy
Labels: ready_to_be_merged

#815 [fulen]Add gmvolf 16.11 with GCC 6.20 and MVAPICH2.3
  easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-6.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.30-GCCcore-6.2.0.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-gmvapich2-16.11.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-6.2.0.eb
  easybuild/easyconfigs/g/GCC/GCC-6.2.0-2.30.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.2.0.eb
  easybuild/easyconfigs/g/gmvapich2/gmvapich2-16.11.eb
  easybuild/easyconfigs/g/gmvolf/gmvolf-16.11.eb
  easybuild/easyconfigs/h/help2man/help2man-1.47.6-GCCcore-6.2.0.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.8-gmvolf-16.11.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-6.2.0.eb
  easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-2.3-GCC-6.2.0-2.30.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.20-GCC-6.2.0-2.30.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmvapich2-16.11-OpenBLAS-0.2.20.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-6.2.0.eb
Labels: ready_to_be_merged

#926 [kesch] Update MCH-RH7.3-17.02
  jenkins-builds/MCH-RH7.3-17.02
Labels: enhancement

#930 [daint-gpu] LAMMPS with PLUMED
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08-PLUMED-2.4.3-cuda-9.1.eb
Labels: enhancement

#932 [daint] ospray version update
  easybuild/easyconfigs/o/ospray/ospray-1.7.2-CrayGNU-18.08.eb
Labels: enhancement
