Repository eth-cscs/production, pull requests merged in 2018-07, with the labels that each got.

#674 [dom] Custom EasyBuild buildpath for each machine
  jenkins/JenkinsfileProductionEB
  jenkins/Machines.groovy
Labels: bug

#675 [dom] Expand the buildPath
  jenkins/JenkinsfileProductionEB
Labels: bug

#676 [daint] Fixing symbolic links daint-gpu and daint-mc
  jenkins-builds/daint-gpu
  jenkins-builds/daint-mc
Labels: bug

#685 [dom] Ci/jenkins readme
  jenkins/README.md
Labels: enhancement, ready_to_be_merged

#686 [dom] Perform initial stages on master node
  jenkins/JenkinsfileProductionEB
  jenkins/JenkinsfileRegressionEB
Labels: bug, ready_to_be_merged

#688 [dom] Change buildPath to point to tmp
  jenkins/JenkinsfileTestingEB
Labels: enhancement, ready_to_be_merged

#677 [dom] ABCpy with CrayGNU 18.07
  easybuild/easyconfigs/a/abcpy/abcpy-0.5.1-CrayGNU-18.07-python3.eb
  easybuild/easyconfigs/c/cloudpickle/cloudpickle-0.3.1-CrayGNU-18.07-python3.eb
  easybuild/easyconfigs/g/glmnet/glmnet-2.0.0-CrayGNU-18.07-python3.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.18.2-CrayGNU-18.07-python3.eb
  jenkins-builds/6.0.UP06-18.07-mc
Labels: enhancement

#708 [dom daint fulen kesch monch leone] Add support for fulen
  jenkins/Machines.groovy
  jenkins/README.md
Labels: enhancement

#709 [fulen] Update README.md to include fulen
  README.md
Labels: enhancement

#713 [daint dom] ReFrame 2.14-dev0 easyconfig
  easybuild/easyconfigs/r/reframe/reframe-2.14-dev0.eb
  jenkins-builds/common-SLES12-2016.10
Labels: enhancement

#723 [daint dom] Remove flag hidden
  jenkins-builds/common-SLES12-2016.10
Labels: bug

#722 [dom] libxml2 with python
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.7-CrayGNU-18.07-python2.eb
Labels: enhancement

#729 [dom] Removing PyMySQL from PyExtensions
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.13.1-CrayGNU-18.07.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6.1.1-CrayGNU-18.07.eb
Labels: bug

#740 [dom] Fix production
  jenkins-builds/6.0.UP06-18.07-gpu
  jenkins-builds/6.0.UP06-18.07-mc
Labels: bug

#736 [dom] CP2K and dependencies
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.07-cuda-9.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.07-cuda-9.1.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.07.eb
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.07.psmp
  easybuild/easyconfigs/l/Libint/Libint-1.1.4-CrayGNU-18.07.eb
  easybuild/easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-18.07.eb
  jenkins-builds/6.0.UP06-18.07-gpu
  jenkins-builds/6.0.UP06-18.07-mc
Labels: enhancement

#743 [daint dom] Dry run
  jenkins-builds/production.sh
Labels: enhancement

#742 [dom] VASP recipes for 18.07
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07-cuda-9.1.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07-cuda-9.1.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07.makefile.include
  jenkins-builds/6.0.UP06-18.07-gpu
  jenkins-builds/6.0.UP06-18.07-mc
Labels: enhancement
