Repository eth-cscs/production, pull requests merged in 2019-11, with the labels that each got.

#1402 [daint dom] ELPA with CrayIntel-19.10
  easybuild/easyconfigs/e/ELPA/ELPA-2019.05.001-CrayIntel-19.10.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.05.002-CrayIntel-19.10.eb
Labels: ready_to_be_merged

#1397 [daint dom] spglib-1.14.1 with CrayIntel-19.10
  easybuild/easyconfigs/s/spglib/spglib-1.14.1-CrayIntel-19.10.eb
Labels: ready_to_be_merged

#1396 [daint-gpu dom-gpu] Magma-2.5.1 with CrayIntel-19.10
  easybuild/easyconfigs/m/magma/magma-2.5.1-CrayIntel-19.10-cuda-10.1.eb
Labels: ready_to_be_merged

#1390 [daint dom] libxc-4.3.4 with CrayIntel-19.10
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-19.10.eb
Labels: ready_to_be_merged

#1425 [daint] SLEPc with version workaround from William
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.9.2-CrayIntel-19.10-complex.eb
Labels: ready_to_be_merged

#1426 [daint-gpu] Fix GROMACS 2018.6 PLUMED-2.5.1 recipe
  easybuild/cray_external_modules_metadata-19.10.cfg
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.6-CrayGNU-19.10-PLUMED-2.5.1-cuda-10.1.eb
Labels: bugfix

#1434 [dom-gpu] Custom cdt modulefile with no verbosity
  login/cdt
Labels: enhancement

#1435 [daint-gpu] Adding MATLAB in production
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-mc
Labels: enhancement

#1432 [daint-gpu] CP2K instrumented with perftools-lite 7.1.1
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-19.10-cuda-10.1-pat-7.1.1.eb
Labels: enhancement

#1424 [daint-gpu] spfft new version 0.9.9
  easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.9-CrayGNU-19.10-cuda-10.1-mkl.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.9-CrayIntel-19.10-cuda-10.1.eb
Labels: enhancement

#1423 [daint-gpu] SIRIUS 6.4.2/QE-SIRIUS 6.4-rc for CrayGNU
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.4-rc3-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.2-CrayGNU-19.10-cuda-10.1.eb
Labels: enhancement

#1421 update to SIRIUS-6.4.2 [daint-gpu]
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.4-rc3-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.2-CrayIntel-19.10-cuda-10.1.eb
Labels: enhancement

#1431 [daint-gpu] Add DCA++ CrayGNU 19.10 easyconfigs including MAGMA dependency.
  easybuild/easyconfigs/d/DCA++/DCA++-1.0.1-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/d/DCA++/DCA++-1.0.1-CrayGNU-19.10.eb
  easybuild/easyconfigs/m/magma/magma-2.2.0-CrayGNU-19.10-cuda-10.1.eb
Labels: enhancement
