Repository eth-cscs/production, pull requests merged in 2019-09, with the labels that each got.

#1292 [daint] Create jupyterlab-1.1.1-CrayGNU-18.08.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-18.08.eb
Labels: ready_to_be_merged

#1291 [dom-gpu] Update 7.0.UP00-19.06-gpu
  jenkins-builds/7.0.UP00-19.06-gpu
Labels: enhancement

#1290 [dom-mc] Update 7.0.UP00-19.06-mc
  jenkins-builds/7.0.UP00-19.06-mc
Labels: help wanted

#1296 [kesch] Adding IDL OPR in production
  easybuild/easyconfigs/i/IDL/IDL-8.5.1-OPR.eb
  jenkins-builds/MCH-RH7.5-17.06
  jenkins-builds/production.sh
Labels: bugfix

#1299 [daint] Easyconfig for the bugfix release of ReFrame 2.17.1
  easybuild/easyconfigs/r/reframe/reframe-2.17.1.eb
Labels: bugfix

#1300 [daint-gpu] Update 6.0.UP07-18.08-gpu with JuliaExtensions
  jenkins-builds/6.0.UP07-18.08-gpu
Labels: enhancement

#1307 [dom] Remove duplicate cudatoolkit entries in metadata
  easybuild/cray_external_modules_metadata.cfg
Labels: bugfix

#1308 [dom-gpu] Use newest cudatookit module number
  easybuild/easyconfigs/m/magma/magma-2.4.0-CrayIntel-19.06-cuda-10.1.eb
Labels: enhancement, ready_to_be_merged

#1312 [dom-gpu] Update 7.0.UP00-19.06-gpu
  jenkins-builds/7.0.UP00-19.06-gpu
Labels: bugfix

#1311 [dom-mc] Update 7.0.UP00-19.06-mc
  jenkins-builds/7.0.UP00-19.06-mc
Labels: bugfix

#1313 [dom-mc] Update 7.0.UP00-19.06-mc
  jenkins-builds/7.0.UP00-19.06-mc
Labels: bugfix

#1314 [dom-gpu] Update 7.0.UP00-19.06-gpu
  jenkins-builds/7.0.UP00-19.06-gpu
Labels: bugfix

#1318 [daint-gpu] rename directory to match the recipe's name
  easybuild/easyconfigs/o/oidn/oidn-0.9.0-CrayGNU-18.08.eb
  easybuild/easyconfigs/o/oidn/oidn-0.9.0-CrayGNU-19.06.eb
Labels: bugfix

#1321 [daint] Add easyconfigs for ReFrame 2.17.2, 2.18 and 2.19 for Daint
  easybuild/easyconfigs/r/reframe/reframe-2.17.2.eb
Labels: enhancement

#1324 [dom-gpu] Fixing path for tools in 19.09
  jenkins-builds/7.0.UP01-19.09-gpu
  jenkins-builds/7.0.UP01-19.09-mc
Labels: bugfix

#1327 [dom-gpu] removing old release of jupyter
  easybuild/easyconfigs/j/jupyterhub/jupyterhub-0.9.6-CrayGNU-19.09.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-0.35.2-CrayGNU-19.09.eb
  jenkins-builds/7.0.UP01-19.09-gpu
  jenkins-builds/7.0.UP01-19.09-mc
Labels: bugfix

#1326 [dom-gpu] Removing old HPX releases
  easybuild/easyconfigs/h/HPX/HPX-1.2.0-CrayGNU-19.09.eb
  easybuild/easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.09.eb
  jenkins-builds/7.0.UP01-19.09-gpu
  jenkins-builds/7.0.UP01-19.09-mc
Labels: bugfix

#1325 [dom-gpu] Changing Paraview dependency to Boost 1.70.0
  easybuild/easyconfigs/p/ParaView/ParaView-5.6.0-EGL-CrayGNU-19.09.eb
Labels: bugfix

#1342 [daint-gpu] ParaView 5.7 GPU Final Release set as default.
  easybuild/easyconfigs/p/ParaView/ParaView-5.7.0-EGL-CrayGNU-18.08.eb
  jenkins-builds/6.0.UP07-18.08-gpu
Labels: ready_to_be_merged
