Repository eth-cscs/production, pull requests merged in 2019-10, with the labels that each got.

#1348 [dom daint kesch] Remove leone from supported systems in CI
  jenkins/JenkinsfileProductionEB
  jenkins/JenkinsfileRegressionEB
  jenkins/JenkinsfileTestingEB
  jenkins/Machines.groovy
Labels: enhancement

#1349 [daint-gpu] New recipe for GROMACS with PLUMED
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.6-CrayGNU-18.08-PLUMED-2.5.1-cuda-9.1.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-18.08.eb
Labels: enhancement

#1350 [dom] Change deprecated 'dummy' toolchain to 'SYSTEM'
  easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.09-classic.eb
  easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.09.eb
  easybuild/easyconfigs/c/CrayGNU/CrayGNU-19.09.eb
  easybuild/easyconfigs/c/CrayIntel/CrayIntel-19.09.eb
  easybuild/easyconfigs/c/CrayPGI/CrayPGI-19.09.eb
Labels: enhancement

#1155 [daint-gpu] Add SIRIUS 6.2.0 to GPU production list
  jenkins-builds/6.0.UP07-18.08-gpu
Labels: question

#1142 [dom-gpu] SIRIUS 6.4.0 / spglib 1.14.1 / libxc 4.3.4 (CrayGNU 19.09)
  easybuild/easyconfigs/e/ELPA/ELPA-2019.05.001-CrayGNU-19.09.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-19.09.eb
  easybuild/easyconfigs/m/magma/magma-2.5.1-CrayGNU-19.09-cuda-10.1.eb
  easybuild/easyconfigs/m/magma/make.inc-gcc-2.5.1
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.0-CrayGNU-19.09-cuda-10.1.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.7-CrayGNU-19.09-cuda-10.1.eb
  easybuild/easyconfigs/s/spglib/spglib-1.14.1-CrayGNU-19.09.eb
Labels: enhancement

#1356 [dom-gpu] Latest release of NCO
  easybuild/easyconfigs/n/NCO/NCO-4.8.1-CrayGNU-19.09.eb
  jenkins-builds/7.0.UP01-19.09-gpu
  jenkins-builds/7.0.UP01-19.09-mc
Labels: bugfix

#1361 [daint-gpu] mpi4py 3.0.2 on Piz Daint
  easybuild/easyconfigs/m/mpi4py/mpi4py-3.0.2-CrayGNU-18.08-python3-cuda9.1.eb
Labels: enhancement

#1373 [dom-gpu] CP2K on Dom
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-19.10-cuda-10.1.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-19.10.psmp
Labels: enhancement

#1379 [daint] updated ecCodes to v2.12.2
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.12.2-CrayCCE-18.08.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.12.2-CrayGNU-18.08.eb
Labels: enhancement

#1380 [dom] Fix default CMake version for CLE7
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-mc
Labels: bugfix

#1331 [dom] HPX with APEX for PE 19.10
  easybuild/easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.10-APEX.eb
  easybuild/easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.10.eb
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-mc
Labels: enhancement
