Repository eth-cscs/production, pull requests merged in 2020-09, with the labels that each got.

#1904 [dom] CPMD running with old Intel compiler
  easybuild/easyconfigs/c/CPMD/CPMD-4.3-CrayIntel-20.08-cuda.eb
Labels: bugfix

#1918 [dom-gpu] CP2K with perftools
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.08-cuda-pat.eb
Labels: enhancement

#1922 [daint-gpu] Update production list and machine data
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
  jenkins-builds/daint-gpu
  jenkins-builds/daint-mc
  jenkins/Machines.groovy
Labels: enhancement

#1923 [daint-gpu] Recipes of older VASP 5.4.4 on cdt 20.08
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-20.08-cuda.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-20.08.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-cuda.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel.makefile.include
Labels: enhancement

#1924 [daint-gpu dom-gpu] Horovod PyTorch16 cdt20.08
  easybuild/easyconfigs/h/Horovod/Horovod-0.19.5-CrayGNU-20.08-pt-1.6.0.eb
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-dom-gpu
Labels: enhancement, ready_to_be_merged

#1929 [daint-gpu] Fix Machines.groovy and link to cdt custom modulefile
  jenkins/Machines.groovy
  login/cdt
Labels: bugfix

#1928 [dom daint] Fix mpi configuration of h5py parallel
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-CrayGNU-20.08-python3-parallel.eb
Labels: bugfix

#1916 [dom-gpu] pgi for hackaton
  easybuild/easyconfigs/p/PGI/PGI-20.4.0.eb
  easybuild/easyconfigs/p/PGI/PGI-20.7.0.eb
Labels: ready_to_be_merged

#1938 [daint,dom] jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner.eb
Labels: bugfix

#1941 [daint-mc] CP2K (cpu only) with perftools lite
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.08-pat.eb
Labels: enhancement

#1946 [daint-gpu] QuantumESPRESSO CUDA recipe with perftools-lite
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-20.08-cuda-pat.eb
Labels: enhancement

#1944 [daint-gpu] VASP CUDA recipe with perftools-lite
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08-cuda-pat.eb
Labels: enhancement

#1945 [daint-mc] VASP recipe with perftools-lite
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08-pat.eb
Labels: enhancement

#1947 [daint-mc] QuantumESPRESSO recipe with perftools-lite
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-CrayIntel-20.08-pat.eb
Labels: enhancement

#1956 [dom daint] Add netcdf-python 1.5.4 in production lists
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: ready_to_be_merged

#1958 [daint-gpu] Update deprecated syntax in MATLAB recipe
  easybuild/easyconfigs/m/MATLAB/MATLAB-R2019a.eb
Labels: enhancement

#1960 [daint-gpu dom-gpu] QE/SIRIUS
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-CrayIntel-19.03.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-CrayIntel-19.06.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-CrayIntel-19.09.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-CrayIntel-19.10.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-19.06-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-19.06.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-19.09-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-19.09.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-19.10-cuda-10.1-pat-7.1.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-19.10.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-CrayIntel-19.10.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.4-rc2-CrayIntel-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.4-rc3-CrayGNU-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.4-rc3-CrayIntel-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc1-CrayGNU-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc1-CrayIntel-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc3-CrayGNU-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc3-CrayIntel-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayGNU-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayIntel-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayIntel-20.06-cuda.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayIntel-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/s/SIRIUS/SIRIUS-6.5.3-CrayIntel-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayGNU-19.10-cuda-10.1-mkl.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayIntel-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.7-CrayGNU-18.08-cuda-9.1.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.7-CrayGNU-19.09-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.7-CrayGNU-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.7-CrayIntel-18.08-cuda-9.1.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.8-CrayGNU-19.10-cuda-10.1-mkl.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.8-CrayIntel-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.9-CrayGNU-19.10-cuda-10.1-mkl.eb
  easybuild/deprecated_easyconfigs/s/SpFFT/SpFFT-0.9.9-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayGNU-20.08-cuda.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayIntel-20.08-SIRIUS-6.5.6-cuda.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-20.08-cuda.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayGNU-20.08-cuda-mkl.eb
  easybuild/easyconfigs/s/spglib/spglib-1.16.0-CrayGNU-20.08.eb
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-dom-gpu
Labels: enhancement

#1962 [daint-gpu] NAMD instrumented executable recipes created
  easybuild/easyconfigs/n/NAMD/NAMD-2.13-CrayIntel-20.08-cuda-pat.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.13-CrayIntel-20.08-pat.eb
Labels: enhancement

#1961 [daint-gpu] QE-SIRIUS with perftools-lite
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayGNU-20.08-cuda-pat.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-20.08-cuda-pat.eb
Labels: enhancement

#1964 [daint-gpu] QuantumESPRESSO 6.6a2 (GPU)
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayPGI-20.08.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.08-cuda.eb
Labels: enhancement

#1963 [daint-mc] QuantumESPRESSO 6.6
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-CrayIntel-20.08.eb
Labels: enhancement

#1966 [daint-gpu] Add latest QuantumESPRESSO release in production as non default
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: enhancement

#1949 [dom-mc] PDT version bump
  easybuild/easyconfigs/p/PDT/PDT-3.25.1.eb
  easybuild/easyconfigs/s/Score-P/Score-P-6.0-CrayGNU-20.08-cuda.eb
  easybuild/easyconfigs/s/Score-P/Score-P-6.0-CrayGNU-20.08.eb
Labels: bugfix

#1934 [daint] Update HPX to 1.5.0
  easybuild/easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.08-APEX-cuda.eb
  easybuild/easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.08-APEX.eb
  easybuild/easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.08-cuda.eb
  easybuild/easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.08-nonetworking-cuda.eb
  easybuild/easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.08-nonetworking.eb
  easybuild/easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.08.eb
Labels: enhancement

#1972 [daint] LAMMPS 20.08 with pat
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-cuda-pat.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-pat.eb
Labels: ready_to_be_merged

#1973 [daint,dom] Add HPX 1.5.0 to production lists
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: enhancement
