Repository eth-cscs/production, pull requests merged in 2020-11, with the labels that each got.

#2007 [dom] Update dismissed lists
  jenkins-builds/dismissed/6.0.UP04-17.08-gpu
  jenkins-builds/dismissed/6.0.UP04-17.08-mc
  jenkins-builds/dismissed/6.0.UP07-18.07-gpu
  jenkins-builds/dismissed/6.0.UP07-18.07-mc
  jenkins-builds/dismissed/6.0.UP07-18.08-gpu
  jenkins-builds/dismissed/6.0.UP07-18.08-mc
  jenkins-builds/dismissed/7.0.UP00-19.03-gpu
  jenkins-builds/dismissed/7.0.UP00-19.03-mc
  jenkins-builds/dismissed/7.0.UP00-19.06-gpu
  jenkins-builds/dismissed/7.0.UP00-19.06-mc
  jenkins-builds/dismissed/7.0.UP01-19.09-gpu
  jenkins-builds/dismissed/7.0.UP01-19.09-mc
  jenkins-builds/dismissed/7.0.UP01-19.10-dom-gpu
  jenkins-builds/dismissed/7.0.UP01-19.10-dom-mc
  jenkins-builds/dismissed/7.0.UP01-19.10-gpu
  jenkins-builds/dismissed/7.0.UP01-19.10-mc
  jenkins-builds/dismissed/7.0.UP02-20.06-dom-gpu
  jenkins-builds/dismissed/7.0.UP02-20.06-dom-mc
  jenkins-builds/dismissed/MCH-RH7.3-17.02
  jenkins-builds/dismissed/MCH-RH7.5-17.06
  jenkins-builds/dismissed/MCH-RH7.5-18.12
  jenkins-builds/dismissed/MCH-RH7.6-19.04
  jenkins-builds/dismissed/fulen
  jenkins-builds/dismissed/fulen-RH7.4-18.05
  jenkins-builds/dismissed/kesch
  jenkins-builds/dismissed/leone
  jenkins-builds/dismissed/leone-RHEL6.7EUS-17.06
Labels: clean_up

#2008 [dom] Remove Kesch from machines list
  jenkins/Machines.groovy
Labels: clean_up

#2009 [dom] Update Machines list and EasyBuild modulefile
  easybuild/module/EasyBuild-custom/cscs
  jenkins/Machines.groovy
Labels: enhancement

#2010 [eiger] Add Eiger to production list
  easybuild/cray_external_modules_metadata-20.10.cfg
  easybuild/easyblocks/cpetoolchain.py
  easybuild/easybuild.d/system_wide.cfg
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-cpeGNU-20.10.eb
  easybuild/easyconfigs/c/CMake/CMake-3.18.4.eb
  easybuild/easyconfigs/c/cpeCCE/cpeCCE-20.10.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-20.10.eb
  easybuild/easyconfigs/g/GREASY/GREASY-19.03-cscs-cpeGNU-20.10.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.3-cpeGNU-20.10.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeCCE-20.10.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeGNU-20.10.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-cpeGNU-20.10.eb
  jenkins-builds/1.3.1-20.10-eiger
  jenkins-builds/eiger
  jenkins/JenkinsfileProductionEB
Labels: enhancement

#2012 [eiger] Last stable release of LAMMPS
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-20.10.eb
  jenkins-builds/1.3.1-20.10-eiger
Labels: enhancement

#2013 [eiger] Boost on Eiger
  easybuild/easyblocks/boost.py
  easybuild/easyblocks/boostcray.py
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-cpeGNU-20.10-python3.eb
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-cpeGNU-20.10.eb
  jenkins-builds/1.3.1-20.10-eiger
Labels: enhancement

#2011 [eiger] Updated CDO and metadata with production list for Eiger
  easybuild/cray_external_modules_metadata-20.10.cfg
  easybuild/easyconfigs/c/CDO/CDO-1.9.9-cpeGNU-20.10.eb
  jenkins-builds/1.3.1-20.10-eiger
Labels: enhancement

#2017 [dom-gpu] deps for hpct (sc20)
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-CrayGNU-20.08-python3-hpct.eb
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-python3.patch
  easybuild/easyconfigs/d/dyninst/dyninst-10.2.0-CrayGNU-20.08-python3-hpct.eb
  easybuild/easyconfigs/i/intel-xed/intel-xed-12.0.1-CrayGNU-20.08.eb
  easybuild/easyconfigs/l/libdwarf/libdwarf-20201020-CrayGNU-20.08.eb
  easybuild/easyconfigs/l/libiberty/libiberty-8.3.0-CrayGNU-20.08.eb
  easybuild/easyconfigs/l/libmonitor/libmonitor-36e5cb7-CrayGNU-20.08.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.4.0-CrayGNU-20.08.eb
  easybuild/easyconfigs/l/lzma/lzma-4.32.7-CrayGNU-20.08.eb
  easybuild/easyconfigs/m/mbedtls/mbedtls-v2.24.0-CrayGNU-20.08.eb
  easybuild/easyconfigs/x/xerces-c/xerces-c-3.2.3.eb
  easybuild/easyconfigs/x/xz/xz-5.2.5-CrayGNU-20.08.eb
Labels: ready_to_be_merged

#2019 [eiger] NCO latest release with dependencies
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-cpeGNU-20.10-python3.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.14-cpeGNU-20.10.eb
  easybuild/easyconfigs/n/NCO/NCO-4.9.5-cpeGNU-20.10.eb
  jenkins-builds/1.3.1-20.10-eiger
Labels: enhancement

#2018 [dom-gpu daint-gpu] GROMACS 2019.4 CrayGNU-20.08
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.4-CrayGNU-20.08-cuda.eb
Labels: enhancement, work in progress

#2020 [eiger] Matplotlib and dependencies on Eiger
  easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.2.2-cpeGNU-20.10.eb
  easybuild/easyconfigs/f/freetype/freetype-2.10.4-cpeGNU-20.10.eb
  easybuild/easyconfigs/g/gettext/gettext-0.21.eb
  easybuild/easyconfigs/g/graphviz/graphviz-2.44.1-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.1.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libffi/libffi-3.3-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.5-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.37-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.18-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.9.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-cpeGNU-20.10.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.3.3-cpeGNU-20.10.eb
  easybuild/easyconfigs/n/NASM/NASM-2.15.05-cpeGNU-20.10.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2.eb
  easybuild/easyconfigs/n/nodejs/nodejs-14.15.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-cpeGNU-20.10.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.36-cpeGNU-20.10.eb
  easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.3.3-cpeGNU-20.10.eb
Labels: enhancement

#2024 [eiger] Update production list 1.3.1-20.10-eiger
  jenkins-builds/1.3.1-20.10-eiger
Labels: enhancement

#2025 [eiger] VASP 6.1.0 and dependencies
  easybuild/cray_external_modules_metadata-20.10.cfg
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-cpeGNU.makefile.include
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-cpeGNU-20.10.eb
  jenkins-builds/1.3.1-20.10-eiger
Labels: enhancement

#2028 [eiger] Update 1.3.1-20.10-eiger with Jupyter
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-20.10.eb
  jenkins-builds/1.3.1-20.10-eiger
Labels: ready_to_be_merged

#2027 [eiger] QuantumESPRESSO
  easybuild/easyconfigs/l/libxc/libxc-5.0.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-cpeGNU-20.10.eb
  jenkins-builds/1.3.1-20.10-eiger
Labels: enhancement

#2030 [eiger] Added libuv patch for shasta DVS
  easybuild/easyconfigs/n/nodejs/libuv.patch
  easybuild/easyconfigs/n/nodejs/nodejs-14.15.0-cpeGNU-20.10.eb
Labels: bugfix

#2033 [eiger] Update EasyBuild-custom
  easybuild/module/EasyBuild-custom/cscs
Labels: enhancement

#2035 [dom] Fix netCDF PREFIX
  easybuild/cray_external_modules_metadata-20.10.cfg
Labels: bugfix

#2041 [dom-gpu] Minor changes in UpdateEB
  jenkins/JenkinsfileUpdateEB
Labels: bugfix

#2040 WIP [dom-mc] Updated recipes for cdt/20.10
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-CrayGNU-20.10-python3.eb
  easybuild/easyconfigs/a/Amber/Amber-20-3-0-CrayIntel-20.10.eb
  easybuild/easyconfigs/b/Bison/Bison-3.3.2-CrayIntel-20.10.eb
  easybuild/easyconfigs/b/binutils/binutils-2.32-CrayIntel-20.10.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayIntel-20.10.eb
  easybuild/easyconfigs/c/CDO/CDO-1.9.5-CrayGNU-20.10.eb
  easybuild/easyconfigs/c/CDO/CDO-1.9.5-CrayIntel-20.10.eb
  easybuild/easyconfigs/c/cURL/cURL-7.61.1-CrayGNU-20.10.eb
  easybuild/easyconfigs/c/cftime/cftime-1.0.2.1-CrayGNU-20.10-python3.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-CrayIntel-20.10.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.14-CrayGNU-20.10.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.10-batchspawner.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-CrayIntel-20.10.eb
  easybuild/easyconfigs/n/NCO/NCO-4.8.1-CrayGNU-20.10.eb
  easybuild/easyconfigs/n/ncview/ncview-2.1.7-CrayGNU-20.10.eb
  easybuild/easyconfigs/n/netcdf-python/netcdf-python-1.5.4-CrayGNU-20.10-python3.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-20.10.eb
  jenkins-builds/7.0.UP02-20.10-dom-mc
Labels: enhancement, ready_to_be_merged

#2031 [eiger] Julia, JuliaExtensions and JupyterLab
  easybuild/easyconfigs/j/Julia/Julia-1.5.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-20.10.eb
  jenkins-builds/1.3.2-20.10-eiger
Labels: ready_to_be_merged

#2045 [dom-gpu] Minor changes in UpdateEB
  jenkins/JenkinsfileUpdateEB
Labels: enhancement

#2048 [eiger] Workaround for Lmod on Eiger
  easybuild/easyconfigs/c/cpeCCE/cpeCCE-20.10.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-20.10.eb
Labels: bugfix

#2049 [eiger] jupyterlab-2.2.8-cpeGNU-20.10.eb
  easybuild/easyconfigs/j/jupyterlab/ipython-7.18.1-jupyter.patch
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-20.10.eb
  jenkins-builds/1.3.2-20.10-eiger
Labels: bugfix, enhancement, ready_to_be_merged
