Repository eth-cscs/production, pull requests merged in 2020-01, with the labels that each got.

#1459 [daint-gpu] IDL 872 in production
  easybuild/easyconfigs/i/IDL/IDL-8.7.2-CSCS.eb
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-mc
  jenkins-builds/production.sh
Labels: enhancement

#1466 [daint-gpu dom-gpu] magma-2.5.2 with CMake for CrayIntel
  easybuild/easyconfigs/m/magma/magma-2.5.2-CrayIntel-19.10-cuda-10.1.eb
Labels: ready_to_be_merged

#1471 [daint] Fix login modules
  login/daint-gpu
  login/daint-mc
Labels: bugfix, ready_to_be_merged

#1477 [daint-gpu] SIRIUS 6.4.3, SpFFT 0.9.10
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.3-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.3-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayGNU-19.10-cuda-10.1-mkl.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayIntel-19.10-cuda-10.1.eb
Labels: enhancement

#1479 [dom,daint] Create LAMMPS-7Aug2019-CrayGNU-19.10-PLUMED-2.5.1-cuda-10.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-CrayGNU-19.10-PLUMED-2.5.1-cuda-10.1.eb
Labels: enhancement

#1481 [daint-gpu] SIRIUS 6.4.4 / QE-SIRIUS 6.5-rc1
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc1-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc1-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.4-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.4-CrayIntel-19.10-cuda-10.1.eb
Labels: enhancement

#1487 [daint dom] Fix warning about xalt being loaded in the environment
  easybuild/easybuild.d/system_wide.cfg
Labels: bugfix

#1489 [dom] Update Machines.groovy
  jenkins/Machines.groovy
Labels: bugfix
