Repository eth-cscs/production, pull requests merged in 2020-08, with the labels that each got.

#1769 [dom] jupyterlab-1.1.1-CrayGNU-20.06-batchspawner.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-20.06-batchspawner.eb
Labels: ready_to_be_merged

#1787 [dom-gpu] VASP 6.1.0 CrayIntel 20.06
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.06-cuda.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.06-cuda.makefile.include
  jenkins-builds/7.0.UP02-20.06-gpu-dom
Labels: enhancement

#1794 [dom-gpu] Add CP2K arch file without CUDA version
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-cuda.psmp
Labels: bugfix

#1803 [dom] caliper
  easybuild/easyconfigs/a/adept-utils/adept-utils-606ebad-CrayGNU-20.06-python3.eb
  easybuild/easyconfigs/a/adiak/adiak-0.2.1-CrayGNU-20.06.eb
  easybuild/easyconfigs/c/Caliper/Caliper-2.4.0-CrayGNU-20.06.eb
  easybuild/easyconfigs/c/cppcheck/cppcheck-1.90-CrayGNU-20.06.eb
  easybuild/easyconfigs/d/dyninst/dyninst-10.2.0-CrayGNU-20.06-python3.eb
  easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.3-CrayGNU-20.06.eb
  easybuild/easyconfigs/l/llnl-hires-timers/llnl-hires-timers-e6d8308-CrayGNU-20.06.eb
  easybuild/easyconfigs/p/profvis/profvis-fe18867-CrayGNU-20.06.eb
  easybuild/easyconfigs/u/Uncrustify/Uncrustify-0.70.1-CrayGNU-20.06.eb
  jenkins-builds/7.0.UP02-20.06-gpu-dom
  jenkins-builds/7.0.UP02-20.06-mc-dom
Labels: ready_to_be_merged

#1808 [dom-gpu] QuantumESPRESSO 6.5a1 with CrayPGI
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-20.06-cuda.eb
Labels: bugfix

#1806 [dom] Plumed with CrayIntel
  easybuild/easyconfigs/b/Bison/Bison-3.3.2-CrayIntel-20.06.eb
  easybuild/easyconfigs/b/binutils/binutils-2.32-CrayIntel-20.06.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-CrayIntel-20.06.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-20.06.eb
Labels: enhancement

#1804 [dom-gpu] toolchain upgrade script
  tools/upgrade-tc.py
Labels: enhancement, ready_to_be_merged

#1811 [dom-gpu] QuantumESPRESSO-SIRIUS and dependencies with cdt/20.06
  easybuild/cray_external_modules_metadata-20.06.cfg
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-20.06.eb
  easybuild/easyconfigs/m/magma/magma-2.5.3-CrayIntel-20.06-cuda.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayIntel-20.06-cuda.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.3-CrayIntel-20.06-cuda.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayIntel-20.06-cuda.eb
Labels: bugfix

#1810 [dom-gpu] Update production lists on Dom
  jenkins-builds/7.0.UP02-20.06-gpu-dom
  jenkins-builds/7.0.UP02-20.06-mc-dom
Labels: enhancement

#1815 [daint] add Julia 1.5.0 to production
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-mc
Labels: enhancement

#1814 [dom] Fix mkl-2020 patch and paths
  easybuild/easyconfigs/n/numpy/mkl-2020-sitecfg.patch
  easybuild/easyconfigs/n/numpy/numpy-1.17.2-CrayGNU-20.06.eb
Labels: bugfix

#1812 [dom] Update Jupyter utils recipe and production files
  easybuild/easyconfigs/j/jupyter-utils/jupyter-utils-0.1.eb
  jenkins-builds/7.0.UP02-20.06-gpu-dom
  jenkins-builds/7.0.UP02-20.06-mc-dom
Labels: bugfix

#1813 [dom] Updated ipyparallel recipe for cdt/20.06 and production lists
  easybuild/easyconfigs/i/ipyparallel/ipyparallel-6.2.4-CrayGNU-20.06-python3.eb
  jenkins-builds/7.0.UP02-20.06-gpu-dom
  jenkins-builds/7.0.UP02-20.06-mc-dom
Labels: enhancement

#1818 [dom] Updated ipcmagic recipe and production lists
  easybuild/easyconfigs/i/ipcmagic/ipcmagic-0.1-CrayGNU-20.06.eb
  jenkins-builds/7.0.UP02-20.06-gpu-dom
  jenkins-builds/7.0.UP02-20.06-mc-dom
Labels: bugfix

#1708 [dom-gpu] Add Amber 20 with CUDA
  easybuild/easyconfigs/a/Amber/Amber-20-3-0-CrayIntel-20.06-cuda.eb
  easybuild/easyconfigs/a/Amber/amber20-nvcc.patch
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayIntel-20.06.eb
  jenkins-builds/7.0.UP02-20.06-gpu-dom
Labels: enhancement

#1819 [dom-gpu] Update Paraview 5.8.0 EGL recipe and production list
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-CrayGNU-20.06-EGL-python3.eb
  jenkins-builds/7.0.UP02-20.06-gpu-dom
Labels: bugfix

#1821 [dom-mc] ParaView with Mesa
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-CrayGNU-20.06-OSMesa-python3.eb
  jenkins-builds/7.0.UP02-20.06-mc-dom
Labels: help wanted

#1822 [dom-gpu] VTK with CrayGNU 20.06 EGL
  easybuild/easyconfigs/v/VTK/VTK-9.0.0-CrayGNU-20.06-EGL-python3.eb
  jenkins-builds/7.0.UP02-20.06-gpu-dom
Labels: help wanted

#1775 [dom-mc] jupyterlab-1.2.16-CrayGNU-20.06-batchspawner.eb with Julia[Extensions]
  easybuild/easyconfigs/j/Julia/Julia-1.5.0-CrayGNU-20.06.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.0-CrayGNU-20.06.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.06-batchspawner.eb
Labels: help wanted

#1829 [dom-gpu] Default module for Horovod
  jenkins-builds/7.0.UP02-20.06-gpu-dom
Labels: question

#1776 [dom-gpu] jupyterlab-1.2.16-CrayGNU-20.06-cuda-batchspawner.eb with Julia[Extensions]
  easybuild/easyconfigs/j/Julia/Julia-1.5.0-CrayGNU-20.06-cuda.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.0-CrayGNU-20.06-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.06-batchspawner-cuda.eb
Labels: help wanted

#1831 [dom] New versions of Julia and Jupyterlab in production on Dom
  jenkins-builds/7.0.UP02-20.06-gpu-dom
  jenkins-builds/7.0.UP02-20.06-mc-dom
Labels: enhancement

#1832 [dom] Add .eb extension to jupyterlab-1.1.1 in dom prod lists
  jenkins-builds/7.0.UP02-20.06-gpu-dom
  jenkins-builds/7.0.UP02-20.06-mc-dom
Labels: bugfix

#1834 [dom-gpu] Cray PE 20.08 metadata file
  easybuild/cray_external_modules_metadata-20.08.cfg
Labels: enhancement

#1833 [dom-gpu] Jenkinsfile UpdateEB
  jenkins-builds/7.0.UP01-19.10-dom-gpu
  jenkins-builds/7.0.UP01-19.10-dom-mc
  jenkins-builds/7.0.UP02-20.06-dom-gpu
  jenkins-builds/7.0.UP02-20.06-dom-mc
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
  jenkins-builds/dom-gpu
  jenkins-builds/dom-mc
  jenkins/JenkinsfileUpdateEB
  jenkins/util.groovy
Labels: enhancement

#1840 [dom] xalt 2.8.10 to CDT 20.08 production list
  jenkins-builds/7.0.UP02-20.08-dom-gpu
Labels: enhancement

#1835 [daint-gpu] Horovod-0.19.5-pt-1.6.0
  easybuild/easyconfigs/h/Horovod/Horovod-0.19.5-CrayGNU-19.10-pt-1.6.0.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0.eb
  jenkins-builds/7.0.UP01-19.10-dom-gpu
  jenkins-builds/7.0.UP01-19.10-gpu
Labels: enhancement, ready_to_be_merged

#1837 WIP [dom-mc] Updated recipes for cdt/20.08
  easybuild/easyconfigs/a/Amber/Amber-20-3-0-CrayIntel-20.08.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayIntel-20.08.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.08.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.1-CrayGNU-20.08.eb
  easybuild/easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.08-APEX.eb
  easybuild/easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.08-nonetworking.eb
  easybuild/easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.08.eb
  easybuild/easyconfigs/j/Julia/Julia-1.5.0-CrayGNU-20.08.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.0-CrayGNU-20.08.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.13-CrayIntel-20.08.eb
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: ready_to_be_merged

#1844 [dom-gpu] Fix dom-gpu production list
  jenkins-builds/7.0.UP02-20.08-dom-gpu
Labels: bugfix

#1843 [dom] Update Cray metadata in the EasyBuild custom modulefile
  easybuild/module/EasyBuild-custom/cscs
Labels: bugfix

#1846 [dom] Convert prod lists to unix format
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: bugfix

#1847 [dom] Add CDO and CPMD missing recipes for cdt 20.08
  easybuild/easyconfigs/c/CDO/CDO-1.9.5-CrayGNU-20.08.eb
  easybuild/easyconfigs/c/CDO/CDO-1.9.5-CrayIntel-20.08.eb
  easybuild/easyconfigs/c/CPMD/CPMD-4.3-CrayIntel-20.08-cuda.eb
  easybuild/easyconfigs/c/CPMD/CPMD-4.3-CrayIntel-20.08.eb
Labels: bugfix

#1859 [dom] Fix tool names for dom prod lists
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: bugfix

#1863 [dom-gpu] Fix nvhpc version in dom-gpu production list
  jenkins-builds/7.0.UP02-20.08-dom-gpu
Labels: bugfix

#1845 [dom-gpu] update Amber-20-3-0-CrayIntel-20.08-cuda.eb for 20.08
  easybuild/easyconfigs/a/Amber/Amber-20-3-0-CrayIntel-20.08-cuda.eb
Labels: ready_to_be_merged

#1868 [dom] Use HDF5-1.10.6 recipes for h5py-2.10.0
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.6-CrayGNU-20.08-parallel.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.6-CrayGNU-20.08-serial.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-CrayGNU-20.08-python3-parallel.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-CrayGNU-20.08-python3-serial.eb
Labels: bugfix

#1865 [dom-gpu] Adding ELPA with GPU support
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.08-cuda.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.08-cuda.eb
Labels: enhancement

#1869 [dom-gpu] VASP6 with cdt 20.08
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08-cuda.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-cuda.makefile.include
Labels: enhancement

#1871 [dom-gpu] Add VASP6 GPU in production
  jenkins-builds/7.0.UP02-20.08-dom-gpu
Labels: enhancement

#1876 [daint-gpu] jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
Labels: ready_to_be_merged

#1874 [daint-gpu] Add HWLOC_ROOT to hwloc modules
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.7.eb
  easybuild/easyconfigs/h/hwloc/hwloc-2.0.4.eb
Labels: enhancement

#1877 [daint-gpu] jupyterlab-1.2.16-CrayGNU-19.10-cuda-10.1-batchspawner.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-19.10-cuda-10.1-batchspawner.eb
Labels: ready_to_be_merged

#1879 [dom] caliper
  easybuild/easyconfigs/a/adept-utils/adept-utils-606ebad-CrayGNU-20.08-python3.eb
  easybuild/easyconfigs/a/adiak/adiak-0.2.1-CrayGNU-20.08.eb
  easybuild/easyconfigs/c/Caliper/Caliper-2.4.0-CrayGNU-20.08.eb
  easybuild/easyconfigs/c/cppcheck/cppcheck-1.90-CrayGNU-20.08.eb
  easybuild/easyconfigs/d/dyninst/dyninst-10.2.0-CrayGNU-20.08-python3.eb
  easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.3-CrayGNU-20.08.eb
  easybuild/easyconfigs/l/llnl-hires-timers/llnl-hires-timers-e6d8308-CrayGNU-20.08.eb
  easybuild/easyconfigs/p/profvis/profvis-fe18867-CrayGNU-20.08.eb
  easybuild/easyconfigs/u/Uncrustify/Uncrustify-0.70.1-CrayGNU-20.08.eb
Labels: ready_to_be_merged

#1880 [dom] adding caliper to production list + sorting
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: ready_to_be_merged

#1883 [dom-gpu] jupyterlab 1.2.16 with julia 1.5.0 (PE 20.08)
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
Labels: ready_to_be_merged

#1886 [daint,dom] Create CMake-3.18.1.eb
  easybuild/easyconfigs/c/CMake/CMake-3.18.1.eb
Labels: bugfix

#1885 [dom-gpu] Decrease xalt data volume
  easybuild/easyconfigs/x/xalt/xalt-xalt-2.8.10.bindata.patch
Labels: enhancement, ready_to_be_merged

#1888 [dom-gpu] Update ELPA dependency of SIRIUS
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-20.08-cuda.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.3-CrayIntel-20.08-cuda.eb
Labels: enhancement

#1893 [dom-gpu] scorep+cuda
  easybuild/easyconfigs/s/Score-P/Score-P-6.0-CrayGNU-20.08-cuda.eb
  jenkins-builds/7.0.UP02-20.08-dom-gpu
Labels: ready_to_be_merged

#1892 [daint-mc] Add OpenFOAM-7 and SCOTCH 6.0.9
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7.0-CrayGNU-19.10.eb
  easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-7.0-20200508
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.9-CrayGNU-19.10.eb
Labels: ready_to_be_merged

#1895 [daint-mc] Changing SCOTCH dependency of OF7
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7.0-CrayGNU-19.10.eb
  easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-7.0-20200508
Labels: ready_to_be_merged
