Repository eth-cscs/production, pull requests merged in 2020-05, with the labels that each got.

#1603 [tsa, TSAtds] Downgrade rstudio version to 1.1.463
  easybuild/easyconfigs/r/rstudio/rstudio-1.1.463.eb
  jenkins-builds/MCH-RH7.6-19.04
  jenkins-builds/MCH-RH7.7-19.04
Labels: bugfix

#1613 [dom-gpu] Fix libcusmm build with CP2K
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10-cuda-10.1.psmp
Labels: bugfix

#1620 [daint-gpu] CP2K 7.1 optimised build
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10-cuda-10.1.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10.psmp
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-19.10.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.14-CrayGNU-19.10.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.14-CrayIntel-19.10.eb
Labels: enhancement

#1624 [daint-gpu] CP2K dependency libsmm with Intel MKL
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10.psmp
Labels: enhancement

#1615 [daint,dom] Add jupyter-utils
  easybuild/easyconfigs/j/jupyter-utils/jupyter-utils-0.1.eb
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-gpu-dom
  jenkins-builds/7.0.UP01-19.10-mc
  jenkins-builds/7.0.UP01-19.10-mc-dom
Labels: enhancement, ready_to_be_merged

#1625 [dom-mc] VASP 6.1.0 multicore
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07-cuda-9.1.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.08-cuda-9.1.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.08.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03-cuda-10.0.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.06-cuda-10.1.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.06.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.09-cuda-10.1.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.09.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-cuda-10.1.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-19.10.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-19.10.makefile.include
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-CrayIntel-19.10.eb
Labels: enhancement

#1606 [dom-gpu] Tool for generating Easyconfig diffs
  tools/ebdiff.py
Labels: enhancement

#1642 [daint TSAtds] Add recipe for ReFrame version 3.0-dev6
  easybuild/easyconfigs/r/reframe/reframe-3.0-dev6.eb
Labels: enhancement

#1645 [daint-gpu] VASP 6.1.0 gpu
  easybuild/easyconfigs/m/magma/magma-2.5.3-CrayPGI-19.10-cuda-10.1.eb
  easybuild/easyconfigs/q/QD/QD-2.3.22-CrayPgi-19.10.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayPGI-19.10-cuda-10.1.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayPGI-19.10-cuda-10.1.makefile.include
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-CrayPGI-19.10.eb
Labels: enhancement

#1650 [dom] Use Buildah-1.14.8.eb in dom production builds
  jenkins-builds/7.0.UP01-19.10-gpu-dom
  jenkins-builds/7.0.UP01-19.10-mc-dom
Labels: ready_to_be_merged

#1652 [dom daint TSAtds] Add ReFrame env variables
  easybuild/easyconfigs/r/reframe/reframe-3.0-dev6.eb
Labels: bugfix

#1653 [daint-gpu] Adding make targets for QE6.5a1
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-19.10-cuda-10.1.eb
Labels: enhancement
