Repository eth-cscs/production, pull requests merged in 2020-12, with the labels that each got.

#2052 [eiger] Update 1.3.2-20.10-eiger
  jenkins-builds/1.3.2-20.10-eiger
Labels: ready_to_be_merged

#2053 [tsa] Create production stack PE20.08
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2-nocuda.eb
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2.eb
  easybuild/easyconfigs/p/PrgEnv-pgi/PrgEnv-pgi-tsa-20.4-nocuda.eb
  easybuild/easyconfigs/p/PrgEnv-pgi/PrgEnv-pgi-tsa-20.4.eb
  jenkins-builds/MCH-PE20.08
  jenkins-builds/dismissed/MCH-PE20.06
  jenkins-builds/dismissed/MCH-PE20.08-dev0
  jenkins-builds/tsa
  jenkins/Machines.groovy
Labels: ready_to_be_merged

#2060 [eiger] Workaround for QE recipe
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-cpeGNU-20.10.eb
Labels: bugfix, ready_to_be_merged

#2054 [daint-gpu] NAMD version update
  easybuild/easyconfigs/c/Charm++/Charm++-6.10.2-CrayIntel-20.08.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-CrayIntel-20.08-cuda.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-CrayIntel-20.08.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14.patch
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-CrayIntel-20.08.eb
Labels: enhancement

#2034 [eiger] CP2K and dependencies
  easybuild/easyconfigs/b/Bison/Bison-3.7-cpeGNU-20.10.eb
  easybuild/easyconfigs/b/binutils/binutils-2.35.1-cpeGNU-20.10.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-cpeGNU-20.10.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-cpeGNU.psmp
  easybuild/easyconfigs/e/ELPA/ELPA-2020.05.001-cpeGNU-20.10.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-cpeGNU-20.10.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/Libint-CP2K/Libint-CP2K-2.6.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.1-cpeGNU-20.10.eb
  jenkins-builds/1.3.1-20.10-eiger
Labels: enhancement

#2072 [eiger] PROJ and dependencies
  easybuild/easyconfigs/l/libreadline/libreadline-8.1-cpeGNU-20.10.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-cpeGNU-20.10.eb
  easybuild/easyconfigs/p/PROJ/PROJ-7.2.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.34.0-cpeGNU-20.10.eb
Labels: enhancement

#2071 [eiger] ecCodes with libaec dependency
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.19.1-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libaec/libaec-1.0.4-cpeGNU-20.10.eb
Labels: enhancement

#2073 [daint] Make use of cray-mpich MPI package
  spack/daint/packages.yaml
Labels: enhancement

#2076 [dom] Switch from cdt to cdt-cuda for 20.10
  easybuild/easyconfigs/c/CrayCCE/CrayCCE-20.10.eb
  easybuild/easyconfigs/c/CrayGNU/CrayGNU-20.10.eb
  easybuild/easyconfigs/c/CrayIntel/CrayIntel-20.10.eb
  easybuild/easyconfigs/c/CrayPGI/CrayPGI-20.10.eb
  jenkins-builds/dom-gpu
  jenkins-builds/dom-mc
Labels: enhancement

#2063 [eiger] NAMD 2.14
  easybuild/easyconfigs/c/Charm++/Charm++-6.10.2-cpeGNU-20.10.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeGNU-20.10.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-cpeGNU-20.10.eb
  jenkins-builds/1.3.2-20.10-eiger
Labels: ready_to_be_merged

#2077 [dom] FFmpeg with 20.10
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.2.2-CrayGNU-20.10.eb
Labels: bugfix

#2078 [dom] Update FFmpeg and NASM with cleanup
  easybuild/deprecated_easyconfigs/f/FFmpeg/FFmpeg-2.8.7-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/f/FFmpeg/FFmpeg-2.8.7-CrayGNU-2016.03.eb
  easybuild/deprecated_easyconfigs/f/FFmpeg/FFmpeg-2.8.7-CrayGNU-2016.11.eb
  easybuild/deprecated_easyconfigs/f/FFmpeg/FFmpeg-2.8.7-gmvolf-15.11.eb
  easybuild/deprecated_easyconfigs/f/FFmpeg/FFmpeg-4.1-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/f/FFmpeg/FFmpeg-4.2.2-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/f/FFmpeg/FFmpeg-4.2.2-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.11.06-gmvolf-15.11.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.11.06-gmvolf-2015a.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.11.08-CrayGNU-2016.03.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.12.01-CrayGNU-2016.03.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.12.01-gmvolf-15.11.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.12.02-CrayGNU-2016.06.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.12.02-CrayGNU-2016.09.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.12.02-CrayGNU-2016.10.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.12.02-CrayGNU-2016.11.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.12.02-GCC-5.4.0-2.26.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.12.02-gmvolf-17.02.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.13.01-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.13.01.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.13.03-CrayGNU-18.07.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.13.03-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.13.03.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.14.02-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.14.02-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.14.02-CrayGNU-20.10.eb
  easybuild/deprecated_easyconfigs/n/NASM/NASM-2.14.02-gmvolf-18.12.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.3.1-CrayGNU-20.10.eb
  easybuild/easyconfigs/n/NASM/NASM-2.15.05-CrayGNU-20.10.eb
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
  jenkins-builds/7.0.UP02-20.10-dom-gpu
  jenkins-builds/7.0.UP02-20.10-dom-mc
Labels: enhancement

#2079 [daint] Fix Piz Daint production list
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.2.2-CrayGNU-20.08.eb
  easybuild/easyconfigs/n/NASM/NASM-2.14.02-CrayGNU-20.08.eb
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
Labels: bugfix

#2081 [dom-gpu] Add missing recipes
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.10-batchspawner-cuda.eb
  easybuild/easyconfigs/n/nvhpc/nvhpc-2020_209-cuda-11.0.eb
  easybuild/easyconfigs/p/pycuda/pycuda-2018.1.1-CrayGNU-20.10-python3-cuda.eb
  jenkins-builds/7.0.UP02-20.10-dom-gpu
Labels: bugfix

#2083 [dom-gpu] Remove Amber from dom-gpu
  jenkins-builds/7.0.UP02-20.10-dom-gpu
Labels: bugfix

#2085 [dom-gpu] Remove NAMD 2.13 from dom-gpu
  jenkins-builds/7.0.UP02-20.10-dom-gpu
Labels: bugfix

#2087 [dom-gpu] Add recipe for magma 2.5.4
  easybuild/easyconfigs/m/magma/magma-2.5.4-CrayIntel-20.10-cuda.eb
  easybuild/easyconfigs/m/magma/make.inc-2.5.4
  jenkins-builds/7.0.UP02-20.10-dom-gpu
Labels: enhancement

#2086 [dom-gpu] Remove magma-2.4.0 from dom-gpu production list
  jenkins-builds/7.0.UP02-20.10-dom-gpu
Labels: bugfix

#2088 [dom] create LAMMPS-29Oct20-CrayGNU-20.10.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-20.10-cuda.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-20.10.eb
  jenkins-builds/7.0.UP02-20.10-dom-gpu
  jenkins-builds/7.0.UP02-20.10-dom-mc
Labels: ready_to_be_merged
