Repository eth-cscs/production, pull requests merged in 2020-04, with the labels that each got.

#1551 [daint-gpu] QE-SIRIUS 6.5.2 for CrayGNU
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.2-CrayGNU-19.10-cuda-10.1.eb
Labels: enhancement

#1533 [daint dom] CPMD 4.3 for CPU and GPU
  easybuild/easyconfigs/c/CPMD/CPMD-4.3-CrayIntel-19.10-cuda-10.1-pat-7.1.1.eb
  easybuild/easyconfigs/c/CPMD/CPMD-4.3-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/c/CPMD/CPMD-4.3-CrayIntel-19.10-pat-7.1.1.eb
  easybuild/easyconfigs/c/CPMD/CPMD-4.3-CrayIntel-19.10.eb
  easybuild/easyconfigs/c/CPMD/patch.cpmd-v4.3-daint.txt
Labels: enhancement

#1532 [daint] new pycuda for PyFR
  easybuild/easyconfigs/p/PyFR/PyFR-1.9.0-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/p/pycuda/pycuda-2019.1.2-CrayGNU-19.10-python3-cuda-10.1.eb
Labels: work in progress

#1565 [daint-gpu] Remove PROJ from hidden-modules list
  easybuild/easybuild.d/system_wide.cfg
Labels: enhancement

#1509 [TSAtds] Add configuration for RH7.7
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2019.03.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20180311.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6.eb
  easybuild/easyconfigs/c/CUDA/CUDA-10.1.243.eb
  easybuild/easyconfigs/d/ddt/ddt-19.0.5-Redhat-7.0.eb
  easybuild/easyconfigs/g/git/git-2.22.0.eb
  easybuild/easyconfigs/i/IDL/IDL-8.5.1-MCH.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-6.7.6-10.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.8-53.eb
  easybuild/easyconfigs/j/Java/Java-1.8.0_212.eb
  easybuild/easyconfigs/n/NCL/NCL-6.2.1.eb
  easybuild/easyconfigs/n/NCL/NCL-6.6.2.eb
  easybuild/easyconfigs/n/nmon/nmon-16g.eb
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2-RH7.7.eb
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2-nocuda.eb
  easybuild/easyconfigs/p/PrgEnv-pgi/PrgEnv-pgi-tsa-19.9-RH7.7.eb
  easybuild/easyconfigs/p/PrgEnv-pgi/PrgEnv-pgi-tsa-19.9-nocuda.eb
  easybuild/easyconfigs/p/Python/Python-2.7.16.eb
  easybuild/easyconfigs/r/reframe/reframe-2.18.eb
  easybuild/easyconfigs/r/rstudio/rstudio-1.2.1335.eb
  easybuild/easyconfigs/v/Vim/Vim-8.1.eb
  easybuild/easyconfigs/v/vampir/vampir-9.6.0.eb
  easybuild/easyconfigs/x/xcb-proto/xcb-proto-1.13.eb
  jenkins-builds/MCH-RH7.7-19.04
  jenkins-builds/tsaTDS
  jenkins/Machines.groovy
Labels: enhancement

#1566 [TSAtds] Fix Machines
  jenkins/Machines.groovy
Labels: bugfix

#1561 [daint-gpu] CP2K 7.1 and dependencies with CrayIntel
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.psmp
  easybuild/easyconfigs/g/GMP/GMP-6.2.0-CrayIntel-19.10.eb
  easybuild/easyconfigs/l/Libint-CP2K/Libint-CP2K-2.6.0-CrayIntel-19.10.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.14-CrayIntel-19.10.eb
Labels: enhancement

#1571 [daint-gpu] Fix Boost download link
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-19.10-python3.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-19.10.eb
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-CrayIntel-19.10.eb
Labels: bugfix

#1567 [daint-mc] QuantumESPRESSO 6.5 with CrayIntel
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-CrayIntel-19.10.eb
Labels: enhancement

#1569 [daint-mc] CP2K 7.1 multicore with CrayIntel
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10.psmp
Labels: enhancement

#1570 [daint-gpu] CP2K 7.1 gpu with CrayIntel
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.psmp
Labels: bugfix

#1568 [daint-gpu] QuantumESPRESSO 6.5a1 gpu with CrayIntel
  README.md
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-CrayIntel-19.10.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-19.10-cuda-10.1.eb
Labels: enhancement

#1572 [daint-gpu] Fix outdated content in README
  README.md
Labels: bugfix

#1580 [dom] caliper
  easybuild/easyconfigs/a/adept-utils/adept-utils-606ebad-CrayGNU-19.10.eb
  easybuild/easyconfigs/a/adiak/adiak-0.2.0-CrayGNU-19.10.eb
  easybuild/easyconfigs/c/Caliper/Caliper-2.3.0-CrayGNU-19.10.dot
  easybuild/easyconfigs/c/Caliper/Caliper-2.3.0-CrayGNU-19.10.eb
  easybuild/easyconfigs/c/callpath/callpath-0d234e1-CrayGNU-19.10.eb
  easybuild/easyconfigs/c/cppcheck/cppcheck-1.90-CrayGNU-19.10.eb
  easybuild/easyconfigs/d/dyninst/dyninst-10.1.0-CrayGNU-19.10.eb
  easybuild/easyconfigs/e/elfutils/elfutils-0.178-CrayGNU-19.10.eb
  easybuild/easyconfigs/g/GOTCHA/GOTCHA-e82b4a1-CrayGNU-19.10.eb
  easybuild/easyconfigs/h/hatchet/hatchet-1.0.1-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/l/libdwarf/libdwarf-20200114-CrayGNU-19.10.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.4.0-CrayGNU-19.10.eb
  easybuild/easyconfigs/l/llnl-hires-timers/llnl-hires-timers-e6d8308-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/profvis/profvis-fe18867-CrayGNU-19.10.eb
  easybuild/easyconfigs/u/Uncrustify/Uncrustify-0.70.1-CrayGNU-19.10.eb
Labels: ready_to_be_merged

#1581 [daint-gpu] Updated QuantumESPRESSO 6.5 in production
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-CrayIntel-19.10.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-19.10-cuda-10.1.eb
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-gpu-dom
  jenkins-builds/7.0.UP01-19.10-mc
  jenkins-builds/7.0.UP01-19.10-mc-dom
Labels: enhancement

#1585 [daint-gpu] DeePMD dependency backports.weakref
  easybuild/easyconfigs/b/backports.weakref/backports.weakref-1.0.post1-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/d/DeePMD/DeePMD-0.10.2-CrayGNU-19.10.eb
Labels: bugfix

#1578 [daint-mc] Add deepmd-kit-1.1.4
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/d/deepmd-kit/deepmd-kit-1.1.4-CrayGNU-19.10.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-deepmd.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0-CrayGNU-19.10-cc.eb
  easybuild/easyconfigs/t/TensorFlow/configure-cscs-v2.1.0.sh
  easybuild/easyconfigs/t/TensorFlow/tensorflow-v2.1.0-cc.patch
Labels: enhancement

#1594 [dom-mc] Renaming EasyBuild recipe according to versionsuffix
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-deepmd-1.1.4.eb
Labels: bugfix

#1596 [dom] Add Buildah/1.14.8-daint in dom's production lists
  jenkins-builds/7.0.UP01-19.10-gpu-dom
  jenkins-builds/7.0.UP01-19.10-mc-dom
Labels: ready_to_be_merged

#1598 [daint, dom] Add libyaml 0.2.4
  easybuild/easyconfigs/l/libyaml/libyaml-0.2.4-CrayGNU-19.10.eb
Labels: ready_to_be_merged

#1602 [dom-gpu] CP2K 7.1 in production
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-gpu-dom
  jenkins-builds/7.0.UP01-19.10-mc
  jenkins-builds/7.0.UP01-19.10-mc-dom
Labels: enhancement
