Repository eth-cscs/production, pull requests merged in 2020-10, with the labels that each got.

#1974 [dom] Update Cray metadata for CDT 20.09
  easybuild/cray_external_modules_metadata-20.09.cfg
Labels: enhancement

#1975 [daint] Update PLUMED-2.5.1 metadata
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-20.08.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-20.08.eb
Labels: bugfix

#1977 [dom daint] Update Celery version for oq-engine
  easybuild/easyconfigs/o/oq-engine/oq-engine-3.9.0-CrayGNU-20.08.eb
Labels: bugfix

#1976 [dom daint] Upgrade PLUMED
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.2.3-CrayGNU-2016.11.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.3.0-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.3.0-CrayGNU-2016.11.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.3.0-CrayIntel-2016.11.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.4.0-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.4.0-CrayIntel-17.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.4.2-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.4.3-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.4.3-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.0-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.0-CrayIntel-18.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-19.03.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-19.06.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-19.09.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-19.10-mpi.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-20.06.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-19.03.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-19.06.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-19.09.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-19.10.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-20.06.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.4-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.6.0-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/plumed-compiler.patch
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.1-CrayGNU-20.08.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.1-CrayIntel-20.08.eb
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: enhancement

#1978 [daint-mc dom-mc] Remove oq-engine from production lists
  jenkins-builds/7.0.UP02-20.08-daint-mc
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: bugfix, ready_to_be_merged

#1982 [daint-gpu] Latest release of ecCodes
  easybuild/deprecated_easyconfigs/e/ecCodes/ecCodes-2.12.2-CrayCCE-18.08.eb
  easybuild/deprecated_easyconfigs/e/ecCodes/ecCodes-2.12.2-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/e/ecCodes/ecCodes-2.12.2-CrayGNU-19.10.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.18.0-CrayGNU-20.08.eb
Labels: enhancement

#1986 [daint-gpu] LAMMPS with user-mofff
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-cuda.eb
Labels: enhancement

#1988 [daint-mc] LAMMPS with user-mofff
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08.eb
Labels: enhancement

#1987 [daint,dom] ipcmagic is back
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.08-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.08-batchspawner.eb
Labels: bugfix, ready_to_be_merged

#1990 WIP: Move older LAMMPS recipes to deprecated folder
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.06-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.06.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-cuda-10.1-pat-7.1.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-deepmd-1.1.4.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-pat-7.1.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-05Nov16-CrayGNU-2016.11-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-05Nov16-CrayGNU-2016.11.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-11Aug2017-CrayGNU-17.08-PLUMED-2.4.0-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-11Aug2017-CrayGNU-17.08-cuda-8.0-pat-6.5.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-11Aug2017-CrayGNU-17.08-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-11Aug2017-CrayGNU-17.08-pat-6.5.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-11Aug2017-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-14May16-CrayGNU-2016.03.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-14May16-CrayGNU-2016.06.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-14May16-CrayGNU-2016.09.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-14May16-CrayGNU-2016.10.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug18-CrayGNU-20.06-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug18-CrayGNU-20.06.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-17.08-deepmd-0.10.2.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08-PLUMED-2.4.3-cuda-9.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08-cuda-9.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08-deepmd-0.10.2.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.03-cuda-10.0.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.03.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.06-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.06.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.09-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.09.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.10-deepmd-0.10.2.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.06.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.10-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.10.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-PLUMED-2.2.3-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-PLUMED-2.2.3.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-cuda-8.0-pat-645-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-cuda-8.0.54.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-pat-645-nogpu.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-CrayGNU-19.10-PLUMED-2.5.1-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/makefile_mpi-cray.patch
Labels: ready_to_be_merged

#1983 [daint-mc] QuantumESPRESSO 6.6 instrumented with CrayPAT
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-CrayIntel-20.08-pat.eb
Labels: enhancement, ready_to_be_merged

#1943 [daint-gpu] gromacs with cdt 20.08 and pat
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.6-CrayGNU-20.08-cuda-pat.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.3-CrayGNU-20.08-cuda-pat.eb
Labels: enhancement

#1838 [daint-gpu] Jenkinsfile RebuildEB
  jenkins/JenkinsfileReBuildEB
  jenkins/README.md
Labels: enhancement

#1996 [dom-gpu] w3m for tools
  easybuild/easyconfigs/g/gc/gc-8.0.4.eb
  easybuild/easyconfigs/w/w3m/w3m-v0.5.3+git20200502-CrayGNU-20.08.eb
Labels: ready_to_be_merged

#2002 [dom] New metadata file for PE 20.10
  easybuild/cray_external_modules_metadata-20.10.cfg
Labels: enhancement

#2003 [dom daint] Add singularity/3.6.4-daint to production lists
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: ready_to_be_merged
