Repository eth-cscs/production, pull requests merged in 2020-06, with the labels that each got.

#1662 [dom-gpu, daint-gpu] Eb template values in nvtop and line_profiler
  easybuild/easyconfigs/l/line_profiler/line_profiler-2.1-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/n/nvtop/nvtop-1.0.0-CrayGNU-19.10-cuda-10.1.eb
Labels: enhancement

#1660 [dom-gpu, daint-gpu] Eb templates in boost
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayGNU-19.10-python2.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayGNU-19.10-python3.eb
Labels: enhancement

#1661 [dom-gpu] Version in Cray toolchain easyconfigs
  easybuild/easyconfigs/c/CrayGNU/CrayGNU-19.10.eb
  easybuild/easyconfigs/c/CrayIntel/CrayIntel-19.10.eb
  easybuild/easyconfigs/c/CrayPGI/CrayPGI-19.10.eb
Labels: enhancement

#1663 [dom-gpu, daint-gpu] use eb templates in HPX
  easybuild/easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-cuda-10.1-APEX.eb
  easybuild/easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-cuda-10.1-nonetworking.eb
  easybuild/easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-cuda-10.1.eb
Labels: enhancement

#1659 [dom-gpu, daint-gpu] Eb templates in dask, numpy, SWIG and PyExtensions
  easybuild/cray_external_modules_metadata-19.10.cfg
  easybuild/easyconfigs/d/dask/dask-2.2.0-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/n/numpy/numpy-1.17.2-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.15.6-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.15.7-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6.5.6-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6.5.7-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/PyExtensionsDS/PyExtensionsDS-3.6.5.7-CrayGNU-19.10.eb
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-CrayGNU-19.10-python3.eb
Labels: enhancement

#1651 [daint-gpu] Add VASP 6.1.0 in production
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-19.10-cuda-10.1.makefile.include
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-gpu-dom
  jenkins-builds/7.0.UP01-19.10-mc
  jenkins-builds/7.0.UP01-19.10-mc-dom
  jenkins-builds/production.sh
Labels: enhancement

#1664 [dom, daint] use eb templates in VTK
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-EGL-CrayGNU-19.10-python3.eb
Labels: ready_to_be_merged

#1666 [dom, daint] Fix boost patch for python[m] includes
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-19.10-python3.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-python3.patch
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-CrayIntel-19.10-python3.eb
Labels: bugfix, ready_to_be_merged

#1669 [dom-gpu, daint-gpu] remove toolchain version from CP2K psmp 6x
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-19.10.eb
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-cuda-10.1.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-cuda-10.1.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-cuda-10.1.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel.psmp
Labels: enhancement

#1670 [daint-gpu] Add GROMACS 2019.4 with PLUMED 2.5.4
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.4-CrayGNU-19.10-PLUMED-2.5.4-cuda-10.1.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.4-CrayGNU-19.10-PLUMED-2.5.4.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.4-CrayGNU-19.10.eb
Labels: enhancement

#1672 [daint-gpu] SIRIUS 6.5.3 with CrayIntel
  easybuild/easyconfigs/m/magma/magma-2.5.3-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.3-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayIntel-19.10-cuda-10.1.eb
Labels: enhancement

#1673 [daint-gpu] CP2K 7.1 with SIRIUS 6.5.3 and CrayIntel
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-SIRIUS-6.5.3-cuda-10.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-SIRIUS-6.5.3-cuda-10.1.psmp
Labels: enhancement

#1656 [TSAtds] Change modules tool for RH7.7
  easybuild/module/EasyBuild-custom/cscs
Labels: ready_to_be_merged

#1654 [TSAtds] Adapt PrgEnv-gnu to prevent errors on module purge
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2-nocuda.eb
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2.eb
Labels: bugfix, ready_to_be_merged

#1675 [TSAtds] Remove Python release suffix
  easybuild/easyconfigs/p/Python/Python-3.7.4-r20.02.eb
  easybuild/easyconfigs/p/Python/Python-3.7.4.eb
Labels: ready_to_be_merged

#1649 [tsa] Change production configuration
  jenkins-builds/MCH-RH7.7-19.04
  jenkins/Machines.groovy
Labels: ready_to_be_merged

#1677 [tsa] Correct symbolic link of tsa for machine file
  jenkins-builds/tsa
Labels: ready_to_be_merged

#1674 [daint-gpu, dom-gpu] VASP: remove toolchain_version from makefile.include
  easybuild/easyconfigs/q/QD/QD-2.3.22-CrayPGI-19.10.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-cuda-10.1-pat-7.1.1.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-cuda-10.1-w90-3.1.0.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-pat-7.1.1.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-w90-3.1.0.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-cuda-10.1-w90-3.1.0.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-cuda-10.1.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-w90-3.1.0.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-19.10.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-cuda-10.1.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayPGI-19.10-cuda-10.1.eb
  easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayPGI-cuda-10.1.makefile.include
Labels: enhancement

#1679 [daint, dom] CrayCCE: use version template
  easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.10.eb
Labels: enhancement

#1686 [tsa] Update production list
  jenkins-builds/MCH-RH7.7-19.04
Labels: enhancement

#1687 [tsa] Adding BUILD_ID to the build path in ProductionEB
  jenkins/JenkinsfileProductionEB
Labels: enhancement

#1676 [dom-gpu, daint-gpu] Amber19: specify cudatoolkit version
  easybuild/easyconfigs/a/Amber/Amber-19-9-17-ff19SB-CrayGNU-19.10-cuda-10.1.eb
Labels: ready_to_be_merged

#1688 [tsa] Add ddt 20.0.3
  easybuild/easyconfigs/d/ddt/ddt-20.0.3-Redhat-7.0.eb
Labels: enhancement

#1682 [dom-gpu] Update version and versionsuffix in CrayCCE-classic
  easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.10-classic.eb
Labels: enhancement

#1689 [daint, dom] rename PyExtensions-python2 in prod files
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-gpu-dom
  jenkins-builds/7.0.UP01-19.10-mc
  jenkins-builds/7.0.UP01-19.10-mc-dom
Labels: enhancement

#1692 [tsa] Fix Python module versions in PyExtension-2.7.16
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-foss-2019b.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-fosscuda-2019b.eb
Labels: enhancement

#1685 [tsa] Add release tag to path variable
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2-nocuda.eb
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2.eb
Labels: bugfix

#1678 [dom,daint] Update jupyterlab-1.1.1-CrayGNU-19.10-batchspawner.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-19.10-batchspawner.eb
Labels: ready_to_be_merged

#1694 [tsa] Fix production PrgEnv-gnu/19.2
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2-RH7.7.eb
  jenkins-builds/TSAtds
Labels: bugfix

#1695 [tsa] Remove extension duplicate
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-foss-2019b.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-fosscuda-2019b.eb
Labels: bugfix, duplicate

#1697 [tsa] Update Buildah version in production list
  jenkins-builds/MCH-RH7.7-19.04
Labels: enhancement

#1700 [tsa] Align OpenMPI easyconfig files
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-PGI-19.9-GCC-8.3.0-cuda-10.1-RH7.7.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-PGI-19.9-GCC-8.3.0-cuda-10.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-gcccuda-2019b-cuda-10.1-RH7.7.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-gcccuda-2019b-cuda-10.1.eb
  jenkins-builds/MCH-RH7.7-19.04
Labels: enhancement

#1699 [tsa] Add subfolder (tag name) to local_path variable
  easybuild/easyconfigs/p/PrgEnv-pgi/PrgEnv-pgi-tsa-19.9-RH7.7.eb
  easybuild/easyconfigs/p/PrgEnv-pgi/PrgEnv-pgi-tsa-19.9-nocuda.eb
Labels: bugfix

#1702 [tsa] Revert open mpi suffix rh7.7
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-PGI-19.9-GCC-8.3.0-cuda-10.1-RH7.7.eb
  easybuild/easyconfigs/p/PrgEnv-pgi/PrgEnv-pgi-tsa-19.9-RH7.7.eb
  jenkins-builds/MCH-RH7.7-19.04
Labels: bugfix

#1691 [daint-gpu, dom-gpu] PyExtensions py3
  easybuild/deprecated_easyconfigs/p/PyExtensions/PyExtensions-3.6.5.6-CrayGNU-19.10.eb
  easybuild/easyconfigs/d/dask/dask-1.0.0-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/d/dask/dask-2.2.0-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/h/h5py/h5py-2.8.0-CrayGNU-19.10-python3-parallel.eb
  easybuild/easyconfigs/h/h5py/h5py-2.8.0-CrayGNU-19.10-python3-serial.eb
  easybuild/easyconfigs/i/IPython/IPython-5.7.0-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/i/IPython/IPython-7.7.0-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/j/jupyterhub/jupyterhub-1.0.0-CrayGNU-19.10.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-19.10-batchspawner.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-19.10.eb
  easybuild/easyconfigs/l/line_profiler/line_profiler-2.1-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/n/netcdf4-python/netcdf-python-1.4.1-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-python3-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/PyExtensionsDS/PyExtensionsDS-python3-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/prereq/prereq-tf-2.2-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.11.0-CrayGNU-19.10.eb
  easybuild/easyconfigs/p/protobuf/protobuf-3.6.0-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/p/pudb/pudb-2018.1-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/s/scorep_binding_python/scorep_binding_python-1.1-CrayGNU-19.10-python3.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.14.0-CrayGNU-19.10-cuda-10.1.168-python3.eb
  easybuild/easyconfigs/t/TensorFlow/configure-cscs-v1.14.0.sh
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-gpu-dom
  jenkins-builds/7.0.UP01-19.10-mc
  jenkins-builds/7.0.UP01-19.10-mc-dom
Labels: enhancement, ready_to_be_merged

#1665 [dom-gpu, daint-gpu] use eb templates in pycuda
  easybuild/easyconfigs/p/pycuda/pycuda-2018.1.1-CrayGNU-19.10-python2-cuda-10.1.eb
  easybuild/easyconfigs/p/pycuda/pycuda-2018.1.1-CrayGNU-19.10-python3-cuda-10.1.eb
  easybuild/easyconfigs/p/pycuda/pycuda-python2.patch
Labels: enhancement

#1706 [dom, daint] eb py templates for ipyparallel
  easybuild/easyconfigs/i/ipyparallel/ipyparallel-6.2.4-CrayGNU-19.10-python3.eb
Labels: enhancement, ready_to_be_merged

#1717 [daint-gpu] CP2K 7.1 with PLUMED 2.6.0
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10-PLUMED-2.6.0-cuda-10.1.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-PLUMED-2.6.0-cuda-10.1.psmp
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.0-CrayGNU-19.10.eb
Labels: enhancement

#1715 [dom-mc, daint-mc] oq-engine: eb templates and pyext3
  easybuild/easyconfigs/o/oq-engine/oq-engine-3.2.0-CrayGNU-19.10.eb
Labels: enhancement

#1713 [dom-gpu, daint-gpu] eb py templates jupyterlab-1.2.4
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.4-CrayGNU-19.10-cuda-10.1-batchspawner.eb
Labels: enhancement, ready_to_be_merged

#1714 [dom daint tsa] Add recipe for ReFrame version 3.1-dev0
  easybuild/easyconfigs/r/reframe/reframe-3.1-dev0.eb
Labels: enhancement
