Repository eth-cscs/production, pull requests merged in 2020-03, with the labels that each got.

#1513 [TSAtds] MCH non-CUDA GNU software stack
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-foss-2019b-python2.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-foss-2019b-python3.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/CDO/CDO-1.9.7.1-foss-2019b.eb
  easybuild/easyconfigs/c/cURL/cURL-7.65.1-foss-2019b.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.13.0-foss-2019b-python3.eb
  easybuild/easyconfigs/f/foss/foss-2019b.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.1-foss-2019b.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.7.2-foss-2019b.eb
  easybuild/easyconfigs/g/GSL/GSL-2.5-foss-2019b.eb
  easybuild/easyconfigs/g/gompi/gompi-2019b.eb
  easybuild/easyconfigs/i/inputproto/inputproto-2.3.2-foss-2019b.eb
  easybuild/easyconfigs/k/kbproto/kbproto-1.0.7-foss-2019b.eb
  easybuild/easyconfigs/l/libX11/libX11-1.6.7-foss-2019b.eb
  easybuild/easyconfigs/l/libXau/libXau-1.0.9-foss-2019b.eb
  easybuild/easyconfigs/l/libXdmcp/libXdmcp-1.1.3-foss-2019b.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.2-foss-2019b.eb
  easybuild/easyconfigs/l/libxcb/libxcb-1.13-foss-2019b.eb
  easybuild/easyconfigs/n/NCO/NCO-4.8.1-foss-2019b.eb
  easybuild/easyconfigs/n/ncview/ncview-2.1.7-foss-2019b.eb
  easybuild/easyconfigs/n/netCDF-C++/netCDF-C++-4.3.0-foss-2019b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.5-foss-2019b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.0-foss-2019b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-GCC-8.3.0.eb
  easybuild/easyconfigs/p/PROJ/PROJ-6.1.1-foss-2019b.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-foss-2019b.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.7.4-foss-2019b.eb
  easybuild/easyconfigs/p/pkg-config/M4-patch_pkg-config.patch
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/r/R/R-3.5.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.1-foss-2019b.eb
  easybuild/easyconfigs/r/Ruby/Ruby-2.4.0-foss-2019b.eb
  easybuild/easyconfigs/r/Ruby/Ruby-2.6.5-foss-2019b.eb
  easybuild/easyconfigs/x/xextproto/xextproto-7.3.0-foss-2019b.eb
  easybuild/easyconfigs/x/xtrans/xtrans-1.4.0-foss-2019b.eb
  easybuild/easyconfigs/y/YAXT/YAXT-0.6.2-foss-2019b.eb
  jenkins-builds/MCH-RH7.7-19.04
  jenkins-builds/TSAtds
  jenkins/Machines.groovy
Labels: enhancement

#1515 [daint dom-gpu] Improve machine name matching test for CI
  jenkins/util.groovy
Labels: bugfix

#1522 [daint-gpu] VASP 5.4.4 with perftools 7.1.1
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-cuda-10.1-pat-7.1.1.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-pat-7.1.1.eb
Labels: enhancement

#1526 [daint-gpu] Update libxc-4.3.4-CrayIntel-19.10.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-19.10.eb
Labels: bugfix

#1527 [daint-gpu] Latest ELPA release with CrayIntel
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-19.10.eb
Labels: enhancement

#1531 [daint] Instrumented NAMD easyconfig created
  easybuild/easyconfigs/n/NAMD/NAMD-2.13-CrayIntel-19.10-cuda-10.1-pat-7.1.1.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.13-CrayIntel-19.10-pat-7.1.1.eb
Labels: enhancement

#1534 [dom-mc,daint-mc] Create LAMMPS-03Mar2020-CrayGNU-19.10.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10.eb
Labels: enhancement

#1528 [daint-gpu] libxc 4.3.4 with CrayGNU
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-19.10.eb
Labels: bugfix

#1525 [dom-gpu] SIRIUS 6.5.1
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc3-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc3-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.1-CrayGNU-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.1-CrayIntel-19.10-cuda-10.1.eb
Labels: enhancement

#1544 [tsa] Account for compatibility mode of modules on RH7.7
  easybuild/module/EasyBuild-custom/cscs
Labels: enhancement

#1536 [dom-gpu] LAMMPS-03Mar2020-CrayGNU-19.10-cuda-10.1-pat-7.1.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-cuda-10.1-pat-7.1.1.eb
Labels: ready_to_be_merged

#1529 [daint-mc] Create perftools-lite verison of LAMMPS LAMMPS-03Mar2020-CrayGNU-19.10-pat-7.1.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-pat-7.1.1.eb
Labels: ready_to_be_merged

#1545 [daint-gpu] Update 7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-mc
Labels: ready_to_be_merged

#1546 Update LAMMPS-03Mar2020-CrayGNU-19.10-pat-7.1.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-pat-7.1.1.eb
Labels: ready_to_be_merged

#1548 [daint-gpu] fix QE+SIRIUS and bump version
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QE-GIPAW-6.2.2-CrayIntel-17.08.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.3-CrayIntel-2016.11-PLUMED-2.3.0.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.2.1-CrayGNU-2016.03.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.3.0-CrayGNU-2016.03.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2015.11.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.06.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.09.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.10-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.10.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.11-cuda-8.0.54.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.11-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.11-pat-645-nogpu.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.11.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.1.0-CrayIntel-17.08-pat-6.5.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.1.0-CrayIntel-17.08.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.1.0-CrayIntel-2016.11.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.2.1-CrayIntel-17.08.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-CrayIntel-18.08.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-gitlab-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-rc3-sirius-CrayIntel-18.08-cuda-9.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4-rc1-sirius-CrayIntel-18.08-cuda-9.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-18.08-cuda-9.1.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.2-CrayIntel-17.08-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.3-CrayIntel-17.08-cuda-8.0.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.4-rc2-CrayIntel-18.08-cuda-9.1.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayIntel-19.10-cuda-10.1.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.2-CrayIntel-19.10-cuda-10.1.eb
  jenkins-builds/7.0.UP01-19.10-gpu
Labels: bugfix, ready_to_be_merged

#1547 [daint-gpu] VASP 5.4.4 with Wannier90 interface
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-cuda-10.1-w90-3.1.0.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-cuda-10.1-w90-3.1.0.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-w90-3.1.0.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-w90-3.1.0.makefile.include
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-CrayIntel-19.10.eb
Labels: enhancement

#1537 [daint-gpu] libxc 4.3.4 with CrayGNU and CMake
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-19.10.eb
Labels: enhancement

#1553 [daint-mc] Fix VASP W90 makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-w90-3.1.0.makefile.include
Labels: bugfix

#1555 [dom daint] Remove ipykernel from production list
  jenkins-builds/7.0.UP01-19.10-gpu
  jenkins-builds/7.0.UP01-19.10-gpu-dom
  jenkins-builds/7.0.UP01-19.10-mc
  jenkins-builds/7.0.UP01-19.10-mc-dom
Labels: bugfix

#1556 [daint] Provide Instrumented version of Amber18
  easybuild/easyconfigs/a/Amber/Amber-18-14-14-CrayGNU-19.10-cuda-10.1-pat7.1.1.eb
Labels: enhancement

#1557 [daint-gpu] Latest ELPA release with CrayGNU
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-19.10.eb
Labels: enhancement

#1559 [dom daint tsa] Add the '--upgrade' option to pip
  easybuild/easyconfigs/r/reframe/reframe-3.0-dev3.eb
Labels: ready_to_be_merged

#1560 [daint-gpu] Amber
  easybuild/easyconfigs/a/Amber/Amber-18-14-14-CrayGNU-19.10-cuda-10.1-pat7.1.1.eb
Labels: enhancement
