Repository eth-cscs/production, pull requests merged in 2021-02, with the labels that each got.

#2127 [daint-gpu] Lammps easyconfig with plumed support created
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-PLUMED-cuda.eb
Labels: enhancement

#2104 [dom-gpu] Add TensorFlow from pypi and corresponding Horovod
  easybuild/easyconfigs/h/Horovod/Horovod-0.21.0-CrayGNU-20.11-tf-2.4.0-pip.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.0-CrayGNU-20.11-pip.eb
Labels: ready_to_be_merged

#2136 [dom-gpu] CP2K 8.1 with PE 20.11
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-cuda.psmp
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-20.11-cuda.eb
  jenkins-builds/7.0.UP02-20.11-dom-gpu
Labels: enhancement

#2137 [dom-mc] CP2K 8.1 with PE 20.11 (multicore)
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU.psmp
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-20.11.eb
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: enhancement

#2128 [daint] Add Julia 1.5.3 and improve Julia admin path handling
  easybuild/easyblocks/julia.py
  easybuild/easyblocks/juliabundle.py
  easybuild/easyblocks/juliapackage.py
  easybuild/easyconfigs/j/Julia/Julia-1.5.3-CrayGNU-20.08-cuda.eb
  easybuild/easyconfigs/j/Julia/Julia-1.5.3-CrayGNU-20.08.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.3-CrayGNU-20.08-cuda.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.3-CrayGNU-20.08.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner.eb
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
  jenkins-builds/7.0.UP02-20.08-dom-gpu
  jenkins-builds/7.0.UP02-20.08-dom-mc
Labels: ready_to_be_merged

#2139 [dom] Add Julia-1.5.3 recipies for PE20.11
  easybuild/easyconfigs/j/Julia/Julia-1.5.3-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/j/Julia/Julia-1.5.3-CrayGNU-20.11.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.3-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.3-CrayGNU-20.11.eb
Labels: ready_to_be_merged

#2133 [dom] Update jupyterlab-1.2.16-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner.eb
Labels: ready_to_be_merged

#2143 [eiger] Update 1.3.2-20.10-eiger
  jenkins-builds/1.3.2-20.10-eiger
Labels: enhancement

#2144 [daint dom eiger tsa] Add createJiraSD to util.groovy
  jenkins/util.groovy
Labels: enhancement

#2146 [daint-gpu] fix loading the NVIDIA Index Library
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.08-EGL-python3.eb
Labels: bugfix

#2147 [dom] Use createJiraSD with RebuildEB
  jenkins/JenkinsfileReBuildEB
  jenkins/util.groovy
Labels: enhancement

#2149 [dom] fix cmake version in pybind11
  easybuild/easyconfigs/p/pybind11/pybind11-2.6.1-CrayGNU-20.11.eb
Labels: bugfix, ready_to_be_merged

#2150 [dom] Update spark
  easybuild/easyconfigs/s/Spark/Spark-2.4.7-CrayGNU-20.11-Hadoop-2.7.eb
  easybuild/easyconfigs/s/Spark/spark-2.4.7-Hadoop-2.7.patch
Labels: bugfix

#2151 [dom] Update production list
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: bugfix

#2153 [dom] Remove PLUMED Intel
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: bugfix

#2152 [dom] Reset CP2K 7.1 as default on Dom
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.11.eb
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: bugfix

#2155 [eiger] Configure Pilatus
  easybuild/cray_external_modules_metadata-21.02.cfg
  easybuild/easyblocks/cpetoolchain.py
  easybuild/easybuild.d/system_wide.cfg
  easybuild/module/EasyBuild-custom/cscs
  jenkins-builds/1.3.2-21.02-pilatus
  jenkins-builds/pilatus
  jenkins/Machines.groovy
Labels: enhancement

#2156 [pilatus] Toolchain recipes and GSL in production list
  easybuild/easyconfigs/c/cpeCCE/cpeCCE-21.02.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.02.eb
  easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.02.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeCCE-21.02.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeGNU-21.02.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeIntel-21.02.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2134 [daint] Update jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner.eb
Labels: ready_to_be_merged

#2160 [pilatus] cpeAMD toolchain with GSL
  easybuild/cray_external_modules_metadata-21.02.cfg
  easybuild/easyblocks/cpetoolchain.py
  easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.02.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeAMD-21.02.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2166 [pilatus] Rename toolchain cpeCCE as cpeCray
  easybuild/easyconfigs/c/cpeCray/cpeCray-21.02.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeCray-21.02.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2167 [pilatus] Reframe 3.4.2 as default on Pilatus
  jenkins-builds/1.3.2-21.02-pilatus
  jenkins/README.md
Labels: enhancement

#2168 [pilatus] Matplotlib 3.3.4 and CP2K 8.1
  easybuild/easyconfigs/b/Bison/Bison-3.7.5-cpeGNU-21.02.eb
  easybuild/easyconfigs/b/Bison/Bison-3.7.5-cpeIntel-21.02.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-cpeGNU-21.02-python3.eb
  easybuild/easyconfigs/b/binutils/binutils-2.36.1-cpeGNU-21.02.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-cpeGNU-21.02.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-cpeIntel-21.02.eb
  easybuild/easyconfigs/c/cpeCCE/cpeCCE-20.10.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-21.02.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-cpeIntel-21.02.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-cpeGNU-21.02.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-cpeIntel-21.02.eb
  easybuild/easyconfigs/f/freetype/freetype-2.10.4-cpeGNU-21.02.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.1-cpeGNU-21.02.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.1-cpeIntel-21.02.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.2.0-cpeGNU-21.02.eb
  easybuild/easyconfigs/l/Libint-CP2K/Libint-CP2K-2.6.0-cpeGNU-21.02.eb
  easybuild/easyconfigs/l/Libint-CP2K/Libint-CP2K-2.6.0-cpeIntel-21.02.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.90-cpeGNU-21.02.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.37-cpeGNU-21.02.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-cpeGNU-21.02.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-cpeIntel-21.02.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.1-cpeGNU-21.02.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-cpeGNU-21.02.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-cpeIntel-21.02.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.3.4-cpeGNU-21.02.eb
  easybuild/easyconfigs/n/NASM/NASM-2.15.05-cpeGNU-21.02.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-cpeGNU-21.02.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-cpeIntel-21.02.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2170 [pilatus] GREASY and GROMACS on Pilatus
  easybuild/easyconfigs/c/CMake/CMake-3.19.6.eb
  easybuild/easyconfigs/g/GREASY/GREASY-19.03-cscs-cpeGNU-21.02.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.5-cpeGNU-21.02.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2169 [pilatus] Jupyterlab and dependencies
  easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.2.3-cpeGNU-21.02.eb
  easybuild/easyconfigs/g/graphviz/graphviz-2.46.1-cpeGNU-21.02.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-21.02.eb
  easybuild/easyconfigs/l/libffi/libffi-3.3-cpeGNU-21.02.eb
  easybuild/easyconfigs/n/nodejs/nodejs-14.16.0-cpeGNU-21.02.eb
Labels: enhancement

#2171 [pilatus] Update jupyterlab-2.2.8-cpeGNU-21.02.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-21.02.eb
Labels: bugfix, enhancement, ready_to_be_merged

#2173 [pilatus] Update production list 1.3.2-21.02-pilatus
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2174 [pilatus] VASP 6.2.0 on Pilatus
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-cpeIntel-21.02.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-cpeIntel.makefile.include
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2172 [pilatus] QuantumESPRESSO 6.7.0
  easybuild/cray_external_modules_metadata-21.02.cfg
  easybuild/easyconfigs/l/libxc/libxc-5.1.2-cpeGNU-21.02.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-cpeGNU-21.02.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2177 [pilatus] NAMD (no smp) build with PE 21.02
  easybuild/easyconfigs/c/Charm++/Charm++-6.10.2-cpeIntel-21.02.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeIntel-21.02.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-cpeIntel-21.02.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2175 [pilatus] ParaView with PE 21.02
  easybuild/easyconfigs/l/LLVM/LLVM-8.0.0-cpeCray-21.02.eb
  easybuild/easyconfigs/m/Mako/Mako-1.1.2-cpeCray-21.02-python3.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.3.3-cpeCray-21.02.eb
  easybuild/easyconfigs/o/oidn/oidn-1.2.4-cpeCray-21.02.eb
  easybuild/easyconfigs/o/ospray/ospray-2.4.0-cpeCray-21.02.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-cpeCray-21.02-OSMesa-python3.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2176 [dom] Add Boost 1.75.0 with CrayPE 20.11
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayGNU-20.11-python3.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayGNU-20.11.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-python3.patch
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-CrayGNU-20.11.eb
Labels: enhancement

#2178 [eiger] LAMMPS python fix
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-20.10.eb
Labels: ready_to_be_merged
