Repository eth-cscs/production, pull requests merged in 2021-01, with the labels that each got.

#2100 [dom daint eiger tsa] Add recipe for Buildah 1.19.0
  easybuild/easyconfigs/b/Buildah/Buildah-1.19.0.eb
Labels: enhancement

#2101 [dom-gpu] Update version of Horovod on the production list
  jenkins-builds/7.0.UP02-20.10-dom-gpu
Labels: bugfix

#2102 [dom] updated GROMACS to version 2020.4 to compile with CUDA 11
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.4-CrayGNU-20.10-cuda.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.4-CrayGNU-20.10.eb
  jenkins-builds/7.0.UP02-20.10-dom-gpu
  jenkins-builds/7.0.UP02-20.10-dom-mc
Labels: bugfix

#2103 [dom-mc] QE 6.7.0 on Dom
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-CrayIntel-20.10.eb
  jenkins-builds/7.0.UP02-20.10-dom-mc
Labels: enhancement

#2059 [eiger] Temporary workaround for toolchain modules
  easybuild/easyconfigs/c/cpeCCE/cpeCCE-20.10.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-20.10.eb
  jenkins-builds/1.3.2-20.10-eiger
Labels: bugfix, ready_to_be_merged

#2105 [dom-gpu] QuantumESPRESSO 6.6a2 with CUDA 11
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.10-cuda.eb
  jenkins-builds/7.0.UP02-20.10-dom-gpu
Labels: bugfix

#2106 [dom-gpu] QuantumESPRESSO 6.6a2 with CrayPGI 20.12 and CUDA 11
  easybuild/cray_external_modules_metadata-20.10.cfg
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.10-cuda.eb
Labels: bugfix

#2107 [dom] Cray external metadata file for PE 20.11 on Dom
  easybuild/cray_external_modules_metadata-20.11.cfg
Labels: enhancement

#2108 [dom-gpu] Remove temporarily Score-P cuda
  jenkins-builds/7.0.UP02-20.10-dom-gpu
Labels: bugfix

#2110 [dom] Switch to cdt-cuda in UpdateEB
  jenkins/JenkinsfileUpdateEB
Labels: bugfix

#2109 [eiger] NAMD - SMP build option update for performance enhancement
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeGNU-20.10.eb
Labels: enhancement

#2111 [dom] Fix if test in UpdateEB
  jenkins/JenkinsfileUpdateEB
Labels: bugfix

#2114 [daint-gpu] CP2K 8.1 (-cuda) on Piz Daint
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.08-cuda.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-cuda.psmp
Labels: enhancement

#2115 [daint-mc] CP2K 8.1 (multicore) recipe and configuration file
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.08.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU.psmp
Labels: enhancement

#2118 [dom] Fix UDUNITS 2.2.26 download
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26.eb
Labels: bugfix

#2119 [dom daint eiger tsa] Updated UDUNITS and expat
  easybuild/easyconfigs/e/expat/expat-2.2.10.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.28.eb
Labels: enhancement

#2117 [dom-mc] Fix ELPA download (multicore)
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.10.eb
Labels: bugfix

#2116 [dom-gpu] Fix ELPA cuda download
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.10-cuda.eb
Labels: bugfix

#2120 [daint] Add CP2K 8.1 in production
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
Labels: enhancement

#2122 [dom-gpu] Add pytorch 1.7.1 cdt/20.11
  easybuild/easyconfigs/n/numpy/numpy-1.18.5-CrayGNU-20.11.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1-CrayGNU-20.11.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.6.1-CrayGNU-20.11.eb
  jenkins-builds/7.0.UP02-20.11-dom-gpu
Labels: enhancement
