Repository eth-cscs/production, pull requests merged in 2021-12, with the labels that each got.

#2542 [eiger pilatus] Deploy ReFrame 3.9.2 on eiger/pilatus
  jenkins-builds/1.4.0-21.08-eiger
  jenkins-builds/1.4.0-21.09-eiger
Labels: ready_to_be_merged

#2543 [daint-gpu] PyTorch-1.10.0
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.10.0-CrayGNU-20.11.eb
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-dom-gpu
Labels: enhancement

#2544 [dom] Update EasyBuild-custom
  easybuild/module/EasyBuild-custom/cscs
Labels: enhancement

#2522 WIP [dom-mc] Updated recipes for PE 21.09
  easybuild/easyconfigs/b/Boost/Boost-1.77.0-CrayGNU-21.09.eb
  easybuild/easyconfigs/c/CDO/CDO-1.9.5-CrayGNU-21.09.eb
  easybuild/easyconfigs/c/CDO/CDO-1.9.5-CrayIntel-21.09.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/c/CPMD/CPMD-4.3-CrayIntel-21.09.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-21.09.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.4-CrayGNU-21.09.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.3-CrayGNU-21.09.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.3-CrayGNU-21.09.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-20Sep21-CrayGNU-21.09.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.6-CrayIntel-21.09.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.8.0-CrayIntel-21.09.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-21.09.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.1-CrayIntel-21.09.eb
  jenkins-builds/1.4.0-21.08-pilatus
  jenkins-builds/7.0.UP03-21.09-dom-mc
  jenkins-builds/dismissed/1.3.1-20.10-eiger
  jenkins-builds/dismissed/1.3.2-20.10-eiger
  jenkins-builds/dismissed/1.3.2-21.02-pilatus
  jenkins-builds/dismissed/1.4.0-21.03-eiger
  jenkins-builds/dismissed/1.4.0-21.03-pilatus
  jenkins-builds/dismissed/1.4.0-21.04-eiger
  jenkins-builds/dismissed/1.4.0-21.04-pilatus
  jenkins-builds/dismissed/1.4.0-21.05-eiger
  jenkins-builds/dismissed/1.4.0-21.05-pilatus
  jenkins-builds/dismissed/1.4.0-21.06-eiger
  jenkins-builds/dismissed/1.4.0-21.06-pilatus
  jenkins-builds/dismissed/1.4.0-21.07-eiger
  jenkins-builds/dismissed/1.4.0-21.07-pilatus
  jenkins-builds/dismissed/1.4.0-21.08-pilatus
  jenkins-builds/dismissed/7.0.UP02-20.08-daint-gpu
  jenkins-builds/dismissed/7.0.UP02-20.08-daint-mc
  jenkins-builds/dismissed/7.0.UP02-20.08-dom-gpu
  jenkins-builds/dismissed/7.0.UP02-20.08-dom-mc
  jenkins-builds/dismissed/7.0.UP02-20.10-dom-gpu
  jenkins-builds/dismissed/7.0.UP02-20.10-dom-mc
  jenkins-builds/dismissed/7.0.UP02-20.11-dom-gpu
  jenkins-builds/dismissed/7.0.UP02-20.11-dom-mc
  jenkins-builds/dismissed/7.0.UP02-21.02-dom-gpu
  jenkins-builds/dismissed/7.0.UP02-21.02-dom-mc
  jenkins-builds/dom-mc
Labels: enhancement, work in progress

#2559 [dom-gpu] ParaView with EGL
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-CrayGNU-21.09-EGL.eb
  jenkins-builds/7.0.UP03-21.09-dom-gpu
Labels: enhancement

#2561 [dom] NAMD: Temporary fix for build on dom with Intel 21.09
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-CrayIntel-21.09-cuda.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-CrayIntel-21.09.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14.patch
Labels: bugfix

#2558 [dom-mc] Paraview with Mesa
  easybuild/easyconfigs/l/LLVM/LLVM-9.0.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/m/Mako/Mako-1.1.6-CrayGNU-21.09.eb
  easybuild/easyconfigs/m/Mesa/Mesa-21.3.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/m/Meson/Meson-0.60.2-CrayGNU-21.09.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.10.2-CrayGNU-21.09.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-CrayGNU-21.09-OSMesa.eb
  jenkins-builds/7.0.UP03-21.09-dom-mc
Labels: enhancement

#2562 [dom] Add NAMD 2.14 in production
  jenkins-builds/7.0.UP03-21.09-dom-gpu
  jenkins-builds/7.0.UP03-21.09-dom-mc
Labels: enhancement

#2560 [dom] Update lists and recipes for Dom
  easybuild/easyconfigs/c/Cython/Cython-0.29.25-CrayGNU-21.09.eb
  easybuild/easyconfigs/c/cftime/site.py
  easybuild/easyconfigs/n/NCO/NCO-5.0.4-CrayGNU-21.09.eb
  easybuild/easyconfigs/n/numpy/mkl-2021-sitecfg.patch
  easybuild/easyconfigs/n/numpy/numpy-1.21.4-CrayGNU-21.09.eb
  easybuild/easyconfigs/p/pycuda/site.py
  jenkins-builds/7.0.UP03-21.09-dom-gpu
  jenkins-builds/7.0.UP03-21.09-dom-mc
  jenkins/JenkinsfileUpdateEB
Labels: enhancement

#2564 [dom] bump spack-config
  easybuild/easyconfigs/s/spack-config/spack-config-1.1-cdt-21.09.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.1-cdt-cuda-21.09.eb
  jenkins-builds/7.0.UP03-21.09-dom-gpu
  jenkins-builds/7.0.UP03-21.09-dom-mc
Labels: enhancement

#2563 [daint] bump spack-config
  easybuild/easyconfigs/s/spack-config/spack-config-1.1-cdt-20.11.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.1-cdt-cuda-20.11.eb
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-mc
Labels: enhancement

#2567 [dom] Deploy singularity/3.8.0-daint on dom
  jenkins-builds/7.0.UP03-21.09-dom-gpu
  jenkins-builds/7.0.UP03-21.09-dom-mc
Labels: ready_to_be_merged

#2568 [pilatus] Update Python packages
  easybuild/easyconfigs/m/Mako/Mako-1.1.5-cpeCray-21.09-python3.eb
  easybuild/easyconfigs/m/Meson/Meson-0.59.2-cpeCray-21.09-python3.eb
  easybuild/easyconfigs/w/wheel/wheel-0.37.0-cpeCray-21.09.eb
Labels: bugfix

#2569 [daint dom eiger pilatus tsa] Update compiler definitions and external metadata
  easybuild/cpe_external_modules_metadata-21.10.cfg
  easybuild/cpe_external_modules_metadata-21.11.cfg
  easybuild/easyconfigs/v/VASP/VASP-6.2.1-cpeIntel.makefile.include
  easybuild/toolchains/compiler/cpe.py
  easybuild/toolchains/compiler/craype.py
Labels: enhancement, bugfix

#2571 [dom-gpu] PyTorch with 21.09
  easybuild/easyconfigs/l/libffi/libffi-3.4.2-CrayGNU-21.09.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.10.1-CrayGNU-21.09.eb
  jenkins-builds/7.0.UP03-21.09-dom-gpu
Labels: enhancement

#2545 [dom daint tsa] Fix name of Libgpg-error
  easybuild/easybuild.d/system_wide.cfg
  easybuild/easyconfigs/b/Buildah/Buildah-1.11.5.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.12.0.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.13.1.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.14.0.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.14.5.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.14.8.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.14.9.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.16.0.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.16.4.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.17.0.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.18.0.eb
  easybuild/easyconfigs/b/Buildah/Buildah-1.19.0.eb
  easybuild/easyconfigs/g/GPGME/GPGME-1.13.1.eb
  easybuild/easyconfigs/g/GPGME/GPGME-1.14.0.eb
  easybuild/easyconfigs/g/GPGME/GPGME-1.15.0.eb
  easybuild/easyconfigs/g/GPGME/GPGME-1.15.1.eb
  easybuild/easyconfigs/l/Libassuan/Libassuan-2.5.3.eb
  easybuild/easyconfigs/l/Libassuan/Libassuan-2.5.4.eb
  easybuild/easyconfigs/l/Libassuan/Libassuan-2.5.5.eb
  easybuild/easyconfigs/l/Libgpg-error/Libgpg-error-1.36.eb
  easybuild/easyconfigs/l/Libgpg-error/Libgpg-error-1.39.eb
  easybuild/easyconfigs/l/Libgpg-error/Libgpg-error-1.42.eb
  easybuild/easyconfigs/r/runc/runc-1.0.0-rc9.eb
  easybuild/easyconfigs/s/skopeo/skopeo-1.1.0.eb
  easybuild/easyconfigs/s/skopeo/skopeo-1.2.0.eb
  easybuild/easyconfigs/s/skopeo/skopeo-1.2.3.eb
  easybuild/easyconfigs/s/skopeo/skopeo-1.3.0.eb
  easybuild/easyconfigs/s/skopeo/skopeo-1.5.1.eb
Labels: ready_to_be_merged

#2572 [dom daint eiger pilatus tsa] Add EasyConfig for skopeo/1.5.2 and update deps
  easybuild/easyconfigs/g/GPGME/GPGME-1.16.0.eb
  easybuild/easyconfigs/l/Libgpg-error/Libgpg-error-1.43.eb
  easybuild/easyconfigs/s/skopeo/skopeo-1.5.2.eb
Labels: enhancement

#2576 [daint-gpu] PyTorch 1.10.1 20.11
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.10.1-CrayGNU-20.11.eb
  jenkins-builds/7.0.UP02-20.11-daint-gpu
Labels: enhancement

#2577 [daint] spack-config 1.3
  easybuild/easyconfigs/s/spack-config/spack-config-1.0-cdt-20.11.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.0-cdt-cuda-20.11.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.1-cdt-20.11.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.2-cdt-20.11.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.3-cdt-20.11.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.3-cdt-cuda-20.11.eb
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-mc
Labels: enhancement

#2578 [dom] spack-config 1.3
  easybuild/easyconfigs/s/spack-config/spack-config-1.0-cdt-21.09.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.1-cdt-21.09.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.1-cdt-cuda-21.09.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.2-cdt-21.09.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.3-cdt-21.09.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.3-cdt-cuda-21.09.eb
  jenkins-builds/7.0.UP03-21.09-dom-gpu
  jenkins-builds/7.0.UP03-21.09-dom-mc
Labels: enhancement

#2580 [pilatus] Paraview v510 cpecray 21.09
  easybuild/easyconfigs/m/Mesa/Mesa-21.3.1-cpeCray-21.09.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.10.0-cpeCray-21.09-OSMesa.eb
  jenkins-builds/1.4.0-21.09-eiger
Labels: enhancement

#2579 [eiger] new ParaView 5.10 for cpeCray-21.08
  easybuild/easyconfigs/p/ParaView/ParaView-5.10.0-cpeCray-21.08-OSMesa.eb
  jenkins-builds/1.4.0-21.08-eiger
Labels: enhancement

#2582 [daint-mc] ParaView OSMesa v510 daint 20.11
  easybuild/easyconfigs/p/ParaView/ParaView-5.10.0-CrayGNU-20.11-EGL.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.10.0-CrayGNU-20.11-OSMesa.eb
  jenkins-builds/7.0.UP02-20.11-daint-mc
Labels: enhancement

#2590 [dom-gpu] Add Horovod in production
  jenkins-builds/7.0.UP03-21.09-dom-gpu
Labels: enhancement
