Repository eth-cscs/production, pull requests merged in 2021-07, with the labels that each got.

#2378 [pilatus] Deploy singularity-3.5.3-eiger on pilatus
  jenkins-builds/1.4.0-21.05-pilatus
Labels: ready_to_be_merged

#2380 [pilatus] Toochain recipes 21.06
  easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.06.eb
  easybuild/easyconfigs/c/cpeCray/cpeCray-21.06.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.06.eb
  easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.06.eb
Labels: enhancement

#2385 [daint] Visit xdmf patch
  easybuild/easyconfigs/v/VTK/VTK-9.0.3-CrayGNU-20.11-EGL-python3.eb
  easybuild/easyconfigs/v/VTK/VTK-9.0.3-CrayGNU-21.02-EGL-python3.eb
  easybuild/easyconfigs/v/Visit/Visit-3.2.0-CrayGNU-20.11.eb
  easybuild/easyconfigs/v/Visit/Visit-3.2.0-CrayGNU-21.02.eb
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-21.02-dom-gpu
Labels: bugfix

#2383 [tsa] MCH-PE20.08-UP01 for RH7.9
  easybuild/easyconfigs/n/ncview/ncview-2.1.7-foss-2019b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.5-foss-2019b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.0-foss-2019b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-GCC-8.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-PGI-20.4-GCC-8.3.0-cuda-10.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-PGI-20.4-GCC-8.3.0-nocuda.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-gcccuda-2019b-cuda-10.1.eb
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2-nocuda.eb
  easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2.eb
  easybuild/easyconfigs/p/PrgEnv-pgi/PrgEnv-pgi-tsa-20.4-nocuda.eb
  easybuild/easyconfigs/p/PrgEnv-pgi/PrgEnv-pgi-tsa-20.4.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-foss-2019b.eb
  easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-fosscuda-2019b.eb
  jenkins-builds/MCH-PE20.08-UP01
  jenkins-builds/tsa
  jenkins/Machines.groovy
Labels: enhancement

#2389 [eiger pilatus] Remove Buildah from Eiger and Pilatus
  jenkins-builds/1.4.0-21.04-eiger
  jenkins-builds/1.4.0-21.04-pilatus
  jenkins-builds/1.4.0-21.05-eiger
  jenkins-builds/1.4.0-21.05-pilatus
  jenkins-builds/1.4.0-21.06-eiger
  jenkins-builds/1.4.0-21.06-pilatus
Labels: clean_up

#2377 [pilatus] bump julia
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-cpeGNU-21.04.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-cpeGNU-21.05.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.0-cpeGNU-21.04.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.0-cpeGNU-21.05.eb
Labels: enhancement

#2393 [eiger pilatus] Add metadata 21.07 and simpler toolchain recipes
  easybuild/cpe_external_modules_metadata-21.07.cfg
  easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.04.eb
  easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.05.eb
  easybuild/easyconfigs/c/cpeCray/cpeCray-21.04.eb
  easybuild/easyconfigs/c/cpeCray/cpeCray-21.05.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.04.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.05.eb
  easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.04.eb
  easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.05.eb
Labels: enhancement

#2392 [eiger pilatus] Add missing recipes of ParaView
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-cpeCray-21.05-OSMesa-python3.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-cpeCray-21.06-OSMesa-python3.eb
Labels: bugfix

#2387 [daint dom] Fix MATLAB
  easybuild/easyblocks/matlab.py
  easybuild/easyconfigs/m/MATLAB/MATLAB-R2021a.eb
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-mc
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
  jenkins-builds/7.0.UP02-21.02-dom-gpu
  jenkins-builds/7.0.UP02-21.02-dom-mc
Labels: bugfix, enhancement, ready_to_be_merged

#2396 [pilatus] Add ReFrame 3.7.0 to the 21.07 eiger/pilatus prod list
  jenkins-builds/1.4.0-21.07-eiger
Labels: ready_to_be_merged

#2391 [eiger pilatus] Remove PyCall with PE 21.06
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.0-cpeGNU-21.05.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.0-cpeGNU-21.06.eb
Labels: bugfix

#2388 [eiger] ffmpeg 4.4 for eiger
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.4-cpeGNU-21.06.eb
  easybuild/easyconfigs/o/ogg/ogg-1.3.1-cpeGNU-21.06.eb
  easybuild/easyconfigs/t/theora/theora-1.2.0alpha1-cpeGNU-21.06.eb
  easybuild/easyconfigs/v/vorbis/vorbis-1.3.3-cpeGNU-21.06.eb
  easybuild/easyconfigs/x/x264/x264-20191217-cpeGNU-21.06.eb
  easybuild/easyconfigs/x/x265/x265-3.2.1-cpeGNU-21.06.eb
  jenkins-builds/1.4.0-21.06-eiger
Labels: enhancement

#2406 WIP [eiger] Updated recipes for PE 21.05
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.4-cpeGNU-21.05.eb
  easybuild/easyconfigs/o/ogg/ogg-1.3.1-cpeGNU-21.05.eb
  easybuild/easyconfigs/t/theora/theora-1.2.0alpha1-cpeGNU-21.05.eb
  easybuild/easyconfigs/v/vorbis/vorbis-1.3.3-cpeGNU-21.05.eb
  easybuild/easyconfigs/x/x264/x264-20191217-cpeGNU-21.05.eb
  easybuild/easyconfigs/x/x265/x265-3.2.1-cpeGNU-21.05.eb
  jenkins-builds/1.4.0-21.05-eiger
Labels: enhancement, ready_to_be_merged

#2410 WIP [pilatus] Updated recipes for PE 21.07
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.4-cpeGNU-21.07.eb
  easybuild/easyconfigs/o/ogg/ogg-1.3.1-cpeGNU-21.07.eb
  easybuild/easyconfigs/t/theora/theora-1.2.0alpha1-cpeGNU-21.07.eb
  easybuild/easyconfigs/v/vorbis/vorbis-1.3.3-cpeGNU-21.07.eb
  easybuild/easyconfigs/x/x264/x264-20191217-cpeGNU-21.07.eb
  easybuild/easyconfigs/x/x265/x265-3.2.1-cpeGNU-21.07.eb
Labels: enhancement, ready_to_be_merged

#2413 [eiger] CP2K 8.2 (PE 21.05)
  easybuild/easyconfigs/c/CP2K/CP2K-8.2-cpeGNU.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-8.2.69b8c2e-cpeGNU-21.05.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-cpeGNU-21.05.eb
  easybuild/easyconfigs/g/GSL/GSL-2.7-cpeGNU-21.05.eb
  easybuild/easyconfigs/l/libvori/libvori-210412-cpeGNU-21.05.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.5-cpeGNU-21.05.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-cpeGNU-21.05.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.2.5-cpeGNU-21.05.eb
  easybuild/easyconfigs/s/SPLA/SPLA-1.5.1-cpeGNU-21.05.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.4-cpeGNU-21.05.eb
  easybuild/easyconfigs/s/spglib/spglib-1.16.0-cpeGNU-21.05.eb
  jenkins-builds/1.4.0-21.05-eiger
Labels: bugfix, enhancement

#2414 WIP [eiger] Updated recipes for PE 21.06
  easybuild/easyconfigs/c/CP2K/CP2K-8.2.69b8c2e-cpeGNU-21.06.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.06.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-cpeGNU-21.06.eb
  easybuild/easyconfigs/g/GSL/GSL-2.7-cpeGNU-21.06.eb
  easybuild/easyconfigs/l/libvori/libvori-210412-cpeGNU-21.06.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.5-cpeGNU-21.06.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-cpeGNU-21.06.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.2.5-cpeGNU-21.06.eb
  easybuild/easyconfigs/s/SPLA/SPLA-1.5.1-cpeGNU-21.06.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.4-cpeGNU-21.06.eb
  easybuild/easyconfigs/s/spglib/spglib-1.16.0-cpeGNU-21.06.eb
  jenkins-builds/1.4.0-21.06-eiger
Labels: bugfix, enhancement, ready_to_be_merged

#2411 [pilatus] Add FFmpeg to 21.07 software stack
  jenkins-builds/1.4.0-21.07-eiger
Labels: enhancement

#2415 [eiger] Fix PLUMED 2.7.1
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-cpeGNU-21.05.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-cpeGNU-21.06.eb
Labels: bugfix

#2416 [daint-mc] CP2K 8.2 with libvori and PLUMED
  easybuild/easyconfigs/c/CP2K/CP2K-8.2-CrayGNU.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-8.2.69b8c2e-CrayGNU-20.11.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-CrayGNU-20.11.eb
  easybuild/easyconfigs/g/GSL/GSL-2.7-CrayGNU-20.11.eb
  easybuild/easyconfigs/l/libvori/libvori-210412-CrayGNU-20.11.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.5-CrayGNU-20.11.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-CrayGNU-20.11.eb
Labels: enhancement

#2417 WIP [pilatus] Updated recipes for PE 21.07
  easybuild/easyconfigs/c/CP2K/CP2K-8.2.69b8c2e-cpeGNU-21.07.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.07.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-cpeGNU-21.07.eb
  easybuild/easyconfigs/g/GSL/GSL-2.7-cpeGNU-21.07.eb
  easybuild/easyconfigs/l/libvori/libvori-210412-cpeGNU-21.07.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.5-cpeGNU-21.07.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-cpeGNU-21.07.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.2.5-cpeGNU-21.07.eb
  easybuild/easyconfigs/s/SPLA/SPLA-1.5.1-cpeGNU-21.07.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.4-cpeGNU-21.07.eb
  easybuild/easyconfigs/s/spglib/spglib-1.16.0-cpeGNU-21.07.eb
  jenkins-builds/1.4.0-21.06-eiger
  jenkins-builds/1.4.0-21.07-eiger
Labels: enhancement, ready_to_be_merged
