Repository eth-cscs/production, pull requests merged in 2021-08, with the labels that each got.

#2421 [eiger pilatus] Deploy ReFrame 3.7.2 on eiger/pilatus
  jenkins-builds/1.4.0-21.04-eiger
  jenkins-builds/1.4.0-21.07-eiger
Labels: ready_to_be_merged

#2420 [pilatus] fix cube deps
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.5-cpeGNU-21.07.eb
  jenkins-builds/1.4.0-21.07-eiger
Labels: ready_to_be_merged

#2419 [eiger] fix cube deps
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.5-cpeGNU-21.04.eb
  jenkins-builds/1.4.0-21.04-eiger
Labels: ready_to_be_merged

#2398 [daint dom eiger pilatus tsa] UpdateEB pipeline and util.groovy
  jenkins/JenkinsfileUpdateEB
  jenkins/JenkinsfileUpdateEB-Pilatus
  jenkins/util.groovy
Labels: enhancement

#2425 [eiger pilatus] CP2K architecture file update
  easybuild/easyconfigs/c/CP2K/CP2K-8.2-cpeGNU.psmp
Labels: enhancement

#2431 [pilatus] Update ELPA and FFTW links for CP2K latest commit
  easybuild/easyconfigs/c/CP2K/CP2K-8.2-CrayGNU.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-8.2-cpeGNU.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-8.2.9cbea64-cpeGNU-21.06.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.2.9cbea64-cpeGNU-21.07.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-cpeGNU-21.06.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-cpeGNU-21.07.eb
Labels: enhancement

#2432 [eiger pilatus] Deploy ReFrame 3.7.3 on eiger/pilatus
  jenkins-builds/1.4.0-21.04-eiger
  jenkins-builds/1.4.0-21.05-eiger
  jenkins-builds/1.4.0-21.06-eiger
  jenkins-builds/1.4.0-21.07-eiger
Labels: ready_to_be_merged

#2437 [dom] jupyterlab-1.2.21-CrayGNU-21.02-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-21.02-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-21.02-batchspawner.eb
Labels: ready_to_be_merged, bugfix

#2436 [daint] Create jupyterlab-1.2.21-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner.eb
Labels: ready_to_be_merged, bugfix

#2443 [daint] Update 7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-mc
Labels: ready_to_be_merged, bugfix

#2441 [daint-mc] Add OpenFOAM v2106 for CrayGNU 20.11
  easybuild/easyconfigs/c/CGAL/CGAL-4.14.3-CrayGNU-20.11.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2106-CrayGNU-20.11.eb
  easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-v2106
Labels: enhancement

#2440 [eiger] Create jupyterlab-2.2.10-cpeGNU-21.04.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-cpeGNU-21.04.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-cpeGNU-21.05.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-cpeGNU-21.06.eb
Labels: bugfix, work in progress

#2444 [eiger] Update 1.4.0-21.04-eiger
  jenkins-builds/1.4.0-21.04-eiger
Labels: ready_to_be_merged, bugfix

#2438 [daint] Create jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner.eb
Labels: ready_to_be_merged, bugfix

#2439 [dom] Create jupyterlab-2.2.10-CrayGNU-21.02-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-21.02-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-21.02-batchspawner.eb
Labels: bugfix

#2446 [dom] Update 7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: ready_to_be_merged

#2445 [daint] Update 7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-mc
  jenkins-builds/7.0.UP02-20.11-dom-gpu
Labels: ready_to_be_merged

#2448 [pilatus] Update production list 21.08
  easybuild/cpe_external_modules_metadata-21.08.cfg
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.07.eb
  easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.07.eb
  easybuild/module/EasyBuild-custom/cscs.lua
  jenkins-builds/1.4.0-21.08-eiger
  jenkins-builds/1.4.0-21.08-pilatus
  jenkins-builds/pilatus
Labels: enhancement

#2457 [dom] Update jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner.eb
Labels: enhancement, ready_to_be_merged, bugfix
