Repository eth-cscs/production, pull requests merged in 2021-11, with the labels that each got.

#2515 [daint-gpu] Gromacs 2021.3
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.3-CrayGNU-21.02-cuda.eb
Labels: enhancement

#2520 [eiger pilatus] Deploy ReFrame 3.9.0 on eiger/pilatus
  jenkins-builds/1.4.0-21.08-eiger
Labels: ready_to_be_merged

#2524 [dom daint tsa eiger pilatus] Add recipe for Skopeo 1.5.1
  easybuild/easyconfigs/s/skopeo/skopeo-1.5.1.eb
Labels: ready_to_be_merged

#2525 [pilatus] Update Pilatus builds
  easybuild/easyconfigs/j/Julia/Julia-1.6.3-cpeGNU-21.09.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.3-cpeGNU-21.09.eb
  easybuild/easyconfigs/o/oidn/oidn-1.4.1-cpeCray-21.09.eb
  easybuild/easyconfigs/o/ospray/ospray-2.7.0-cpeCray-21.09.eb
  easybuild/easyconfigs/v/VTK/VTK-9.1.0-cpeCray-21.09-OSMesa-python3.eb
  jenkins-builds/1.4.0-21.09-eiger
Labels: enhancement, ready_to_be_merged

#2529 [pilatus] configurable-http-proxy-4.2.3-cpeGNU-21.09.eb
  easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.2.3-cpeGNU-21.09.eb
  easybuild/easyconfigs/n/nodejs/nodejs-14.16.0-cpeGNU-21.09.eb
Labels: ready_to_be_merged

#2530 [pilatus] graphviz-2.46.1-cpeGNU-21.09.eb
  easybuild/easyconfigs/g/graphviz/graphviz-2.46.1-cpeGNU-21.09.eb
Labels: ready_to_be_merged

#2531 [pilatus] libffi-3.3-cpeGNU-21.09.eb
  easybuild/easyconfigs/l/libffi/libffi-3.3-cpeGNU-21.09.eb
Labels: ready_to_be_merged

#2534 [eiger pilatus] Reframe/3 9 1 eiger pilatus
  easybuild/easyconfigs/f/FUSE/FUSE-3.10.5.eb
  easybuild/easyconfigs/f/fuse-overlayfs/fuse-overlayfs-1.7.1.eb
  easybuild/easyconfigs/m/Meson/Meson-0.60.1.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.10.2.eb
  jenkins-builds/1.4.0-21.08-eiger
  jenkins-builds/1.4.0-21.09-eiger
Labels: ready_to_be_merged

#2527 [tsa] Updated CDO with ecCodes and libaec
  easybuild/easyconfigs/c/CDO/CDO-1.9.10-foss-2019b.eb
  easybuild/easyconfigs/c/CDO/CDO-1.9.10-fosscuda-2019b.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.23.0-foss-2019b-python3.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.23.0-fosscuda-2019b-python3.eb
  easybuild/easyconfigs/l/libaec/libaec-1.0.6-foss-2019b.eb
  easybuild/easyconfigs/l/libaec/libaec-1.0.6-fosscuda-2019b.eb
Labels: enhancement

#2533 [pilatus] jupyterlab-2.2.10-cpeGNU-21.09.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-cpeGNU-21.09.eb
Labels: ready_to_be_merged

#2535 [eiger pilatus] Update production list 21.09
  jenkins-builds/1.4.0-21.09-eiger
Labels: enhancement, ready_to_be_merged

#2536 [pilatus] jupyterlab-2.2.10-cpeGNU-21.09.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-cpeGNU-21.09.eb
Labels: enhancement

#2537 [dom daint] Add cray specific bind paths for mpi
  easybuild/easyconfigs/s/singularity/singularity-3.6.4-daint.eb
Labels: ready_to_be_merged

#2539 [dom] Add cray specific bind paths for mpi
  easybuild/easyconfigs/s/singularity/singularity-3.8.0-daint.eb
Labels: ready_to_be_merged

#2540 [dom daint pilatus eiger] Remove disabling of remote autodetection
  easybuild/easyconfigs/r/reframe/reframe-3.9.1.eb
Labels: ready_to_be_merged
