Repository eth-cscs/production, pull requests merged in 2021-03, with the labels that each got.

#2082 [eiger] CDI
  easybuild/easyconfigs/c/CDI/CDI-1.9.9-cpeGNU-20.10.eb
  jenkins-builds/1.3.2-20.10-eiger
Labels: enhancement

#2179 [daint] Add Boost 1.75.0 with CrayGNU 20.08
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayGNU-20.08.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayIntel-20.08.eb
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
Labels: enhancement

#2180 [daint dom] Set h5py parallel default
  jenkins-builds/7.0.UP02-20.08-daint-gpu
  jenkins-builds/7.0.UP02-20.08-daint-mc
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: bugfix

#2181 [pilatus] ecCodes on Pilatus
  easybuild/easyconfigs/c/CDO/CDO-1.9.9-cpeGNU-20.10.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.20.0-cpeGNU-21.02.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.25-cpeGNU-21.02.eb
  easybuild/easyconfigs/l/libaec/libaec-1.0.4-cpeGNU-21.02.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.36-cpeGNU-20.10.eb
Labels: enhancement

#2182 [pilatus] PROJ 8 and dependencies
  easybuild/easyconfigs/l/libreadline/libreadline-8.1-cpeGNU-21.02.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-cpeGNU-21.02.eb
  easybuild/easyconfigs/p/PROJ/PROJ-8.0.0-cpeGNU-21.02.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.34.1-cpeGNU-21.02.eb
Labels: enhancement

#2183 [eiger] Restore recipe of CDO 1.9.9 in production
  easybuild/easyconfigs/c/CDO/CDO-1.9.9-cpeGNU-20.10.eb
Labels: bugfix

#2184 [daint-gpu] update VMD to the latest 1.9.4
  easybuild/easyconfigs/v/VMD/VMD-1.9.4.eb
  jenkins-builds/7.0.UP02-20.08-daint-gpu
Labels: enhancement

#2187 [pilatus] LAMMPS with PE 21.02
  easybuild/easybuild.d/system_wide.cfg
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.3.2-cpeGNU-21.02.eb
  easybuild/easyconfigs/g/gettext/gettext-0.21-cpeGNU-21.02.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-21.02.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-cpeGNU-21.02.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-cpeGNU-21.02.eb
  easybuild/easyconfigs/z/zstd/zstd-1.4.9-cpeGNU-21.02.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2190 [dom-gpu] VASP 6.2.0 with PE 20.11
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-20.11-cuda.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-20.11.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-cuda.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel.makefile.include
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: enhancement

#2196 [pilatus] Add ReFrame 3.5.0 to the production list of pilatus
  jenkins-builds/1.3.2-21.02-pilatus
Labels: ready_to_be_merged

#2194 [pilatus] Add Amber 20 using intel for pilatus
  easybuild/easyconfigs/a/Amber/Amber-20-15-9-cpeIntel-21.02.eb
  jenkins-builds/1.3.2-21.02-pilatus
Labels: enhancement

#2198 [dom] cpmd perftools recipe
  easybuild/easyconfigs/c/CPMD/CPMD-4.1-CrayIntel-20.11-pat.eb
Labels: enhancement

#2197 [dom] missing recipes for ParaView 5.9 builds
  easybuild/easyconfigs/o/oidn/oidn-1.2.4-CrayGNU-20.11.eb
  easybuild/easyconfigs/o/ospray/ospray-2.4.0-CrayGNU-20.11.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.11-EGL-python3.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.11-OSMesa-python3.eb
Labels: bugfix

#2200 [dom] NAMD easyconfing created with perftools for CrayIntel 20.11
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-CrayIntel-20.11-cuda-pat.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-CrayIntel-20.11-pat.eb
Labels: enhancement

#2208 [dom] VASP recipes with CrayPAT 20.11
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-20.11-cuda-pat.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-20.11-pat.eb
Labels: enhancement

#2212 [dom] cpmd
  easybuild/easyconfigs/c/CPMD/CPMD-4.1-CrayIntel-20.11-pat.eb
Labels: bugfix

#2210 [dom-gpu] CP2K 7.1 and 8.1 with CrayPAT 20.11
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.11-cuda-pat.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11-cuda-pat.eb
Labels: enhancement, ready_to_be_merged

#2222 [dom] Update jupyterlab-2.0.2-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.11-batchspawner.eb
Labels: ready_to_be_merged

#2226 [eiger] Update jupyterlab-2.2.8-cpeGNU-20.10.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-20.10.eb
Labels: ready_to_be_merged

#2228 [daint-gpu] SpFFT 0.9.10 isn't compatible with cuda 11, upgrade it
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.1-CrayGNU-20.11-cuda-mkl.eb
Labels: bugfix

#2232 [daint-mc] Materials were missing from install dir
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.11-OSMesa-python3.eb
Labels: bugfix

#2233 [daint-mc] Updated OF recipes
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-CrayGNU-20.11.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6.0-CrayGNU-20.11.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7.0-CrayGNU-20.11.eb
  easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-5.x
Labels: enhancement, ready_to_be_merged
