Repository eth-cscs/production, pull requests merged in 2021-10, with the labels that each got.

#2491 [daint,dom] Update expat-2.2.10-CrayGNU-20.11.eb
  easybuild/easyconfigs/e/expat/expat-2.2.10-CrayGNU-20.11.eb
Labels: bugfix

#2492 [eiger] major Mesa upgrade for the (upcoming) ParaView v5.10
  easybuild/easyconfigs/l/LLVM/LLVM-9.0.1-cpeCray-21.08.eb
  easybuild/easyconfigs/m/Mesa/Mesa-21.2.1-cpeCray-21.08.eb
  easybuild/easyconfigs/m/Meson/Meson-0.59.1-cpeCray-21.08-python3.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.10.2-cpeCray-21.08-python3.eb
Labels: enhancement

#2493 [daint, dom] Add ipcmagic to jupyterlab
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner.eb
Labels: enhancement, ready_to_be_merged, bugfix

#2486 [dom daint eiger pilatus tsa] Add recipe for ReFrame version 3.8.2
  easybuild/easyconfigs/r/reframe/reframe-3.8.2.eb
Labels: enhancement

#2496 [eiger pilatus] Deploy ReFrame 3.8.2 on eiger/pilatus
  jenkins-builds/1.4.0-21.08-eiger
Labels: ready_to_be_merged
