Repository eth-cscs/production, pull requests merged in 2021-09, with the labels that each got.

#2462 [eiger] Update apps and metadata
  easybuild/module/EasyBuild-custom/cscs
  jenkins-builds/eiger
Labels: enhancement

#2463 [daint dom] Remove HPX from production lists and clean up recipe folder
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.1.0-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.1.0-CrayGNU-18.07.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.1.0-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.1.0-CrayGNU-19.03.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.2.0-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.2.0-CrayGNU-19.03.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.2.0-CrayGNU-19.06.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-18.08-APEX.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.06-APEX.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.06.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.10-APEX.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.10-nonetworking.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-20.06-APEX.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-20.06-nonetworking.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-20.06.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-APEX.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-cuda-10.1-APEX.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-cuda-10.1-nonetworking.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-cuda-10.1.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-nonetworking.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.06-APEX-cuda.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.06-APEX.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.06-cuda.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.06-nonetworking-cuda.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.06-nonetworking.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.06.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.10-APEX-cuda.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.10-APEX.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.10-cuda.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.10-nonetworking-cuda.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.10-nonetworking.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-20.10.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.10-APEX-cuda.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.10-APEX.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.10-cuda.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.10-nonetworking-cuda.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.10-nonetworking.eb
  easybuild/deprecated_easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-20.10.eb
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-mc
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: clean_up

#2465 [daint eiger pilatus tsa] Add recipe for ReFrame version 3.8.1
  easybuild/easyconfigs/r/reframe/reframe-3.8.1.eb
Labels: enhancement

#2468 [eiger pilatus] Deploy ReFrame 3.8.1 on eiger/pilatus
  jenkins-builds/1.4.0-21.08-eiger
Labels: ready_to_be_merged

#2464 [eiger pilatus] Add purge-proof toolchain modules
  easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.08.eb
  easybuild/easyconfigs/c/cpeCray/cpeCray-21.08.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.08.eb
  easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.08.eb
Labels: enhancement

#2471 [dom] Add R kernel to JupyterLab builds
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner.eb
Labels: enhancement, ready_to_be_merged

#2478 [daint dom eiger pilatus tsa] Workarounds for spack config generator
  spack/reframe/spack.py
Labels: bugfix

#2480 [pilatus] Update jupyterlab-2.2.10-cpeGNU-21.08.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-cpeGNU-21.08.eb
Labels: enhancement, ready_to_be_merged

#2481 [dom] update jupyterlab fix typo
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner.eb
Labels: ready_to_be_merged, bugfix

#2476 [eiger pilatus] Old ELPA on Alps and clean-up
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2016.11.001.pre-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2016.11.001.pre-CrayGNU-19.03.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2016.11.001.pre-CrayGNU-19.06.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2016.11.001.pre-CrayGNU-19.09.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2016.11.001.pre-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2016.11.001.pre-CrayGNU-20.06.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2017.11.001-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2017.11.001-CrayIntel-17.08.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2018.05.001-CrayIntel-17.08.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2018.11.001-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.05.001-CrayGNU-19.09.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.05.001-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.05.001-CrayIntel-18.08.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.05.001-CrayIntel-19.10.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.05.001-CrayIntel-20.06.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.05.002-CrayIntel-19.10.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.06.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.10-cuda.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.10.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-19.10.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-20.06.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.05.001-cpeGNU-20.10.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-20.10.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-20.12.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-21.02.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-21.03.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-21.04.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-21.05.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-21.06.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-21.07.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeIntel-21.02.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-cpeIntel-21.04.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2021.05.002-cpeGNU-21.05.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2021.05.002-cpeGNU-21.06.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2021.05.002-cpeGNU-21.07.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-cpeGNU-21.08.eb
Labels: bugfix, clean_up

#2489 [eiger] ABINIT for Eiger
  easybuild/easyconfigs/a/ABINIT/ABINIT-9.4.1-cpeGNU-21.08.eb
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-cpeGNU-21.08.eb
  easybuild/easyconfigs/w/Wannier90/Wannier90-3x_ignore_makeinc.patch
Labels: enhancement

#2490 [pilatus] Update jupyterlab-2.2.10-cpeGNU-21.08.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-cpeGNU-21.08.eb
Labels: ready_to_be_merged, bugfix
