Repository eth-cscs/production, pull requests merged in 2021-05, with the labels that each got.

#2297 [eiger] Update jupyterlab-2.2.8-cpeGNU-21.04.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-21.04.eb
Labels: ready_to_be_merged

#2292 [dom] Bump julia to 1.6.1
  easybuild/easyconfigs/j/Julia/Julia-1.6.1-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.1-CrayGNU-20.11.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.1-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.1-CrayGNU-20.11.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner.eb
Labels: enhancement, ready_to_be_merged

#2265 [daint] Cray PE-aware architecture modulefiles
  login/daint-gpu/.version
  login/daint-gpu/20.08
  login/daint-gpu/20.11
  login/daint-mc/.version
  login/daint-mc/20.08
  login/daint-mc/20.11
Labels: enhancement

#2301 [dom] scalasca
  easybuild/easyconfigs/o/OTF2/OTF2-2.3.eb
  easybuild/easyconfigs/o/OTF2/OTF2-2.3.patch
  easybuild/easyconfigs/s/Scalasca/Scalasca-2.6-CrayGNU-21.02.eb
Labels: ready_to_be_merged

#2302 [dom] Update dom production lists with julia 1.6.1
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: ready_to_be_merged

#2291 [dom daint] Remove JULIA_PKG_SERVER
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11.eb
Labels: enhancement

#2306 [dom-gpu] intel inspector
  easybuild/easyconfigs/i/inspector/inspector-2021.2.0-145.eb
Labels: ready_to_be_merged

#2307 [dom-gpu] intel advisor
  easybuild/easyconfigs/a/advisor/advisor-2021.2.0.eb
Labels: ready_to_be_merged

#2310 [eiger] NAMD with cpeGNU
  easybuild/easyconfigs/c/Charm++/Charm++-6.10.2-cpeGNU-21.04.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeGNU-21.04.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-cpeGNU-21.04.eb
  jenkins-builds/1.4.0-21.04-eiger
Labels: bugfix

#2311 [eiger] scalasca
  jenkins-builds/1.4.0-21.04-eiger
Labels: bugfix

#2320 [dom] Fix CMake on Dom
  easybuild/easyconfigs/c/CMake/CMake-3.14.5.eb
Labels: bugfix

#2325 [daint dom eiger tsa] Fix TMPDIR
  easybuild/module/EasyBuild-custom/cscs
Labels: bugfix

#2329 [eiger] Deploy ReFrame 3.6.0 on eiger
  jenkins-builds/1.4.0-21.04-eiger
Labels: bugfix, enhancement, ready_to_be_merged

#2331 [dom-gpu] pybind11 with CMakePythonPackage
  easybuild/easyconfigs/p/pybind11/pybind11-2.6.1-CrayGNU-20.11.eb
Labels: bugfix

#2330 [daint-gpu] add SIRIUS-7.2.3
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.2.3-CrayGNU-20.11-cuda.eb
Labels: ready_to_be_merged

#2332 [pilatus] Update configuration
  easybuild/alps-external_modules_metadata-21.05.cfg
  jenkins-builds/1.4.0-21.04-pilatus
  jenkins-builds/pilatus
Labels: enhancement

#2333 [eiger pilatus] Add NCL 6.6.2 in production
  jenkins-builds/1.4.0-21.04-eiger
  jenkins-builds/1.4.0-21.04-pilatus
Labels: enhancement

#2138 [eiger] Initial working spack package.yaml file.
  spack/eiger/compilers.yaml
  spack/eiger/packages.yaml
Labels: enhancement
