Repository eth-cscs/production, pull requests merged in 2021-04, with the labels that each got.

#2247 [dom] Update Spack config for version 0.15.4 on dom
  spack/0.15.4/dom/packages.yaml
Labels: enhancement

#2248 [dom] Update Spack config for version 0.16.1 on dom
  spack/0.16.1/dom/packages.yaml
Labels: enhancement

#2249 [dom] Update Spack config for version develop on dom
  spack/dom/packages.yaml
Labels: enhancement

#2251 [daint dom] Clean-up and update libxc
  easybuild/deprecated_easyconfigs/l/libxc/libxc-2.2.2-CrayGNU-2015.11.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-2.2.2-CrayGNU-2016.03.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-2.2.2-CrayGNU-2016.06.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-2.2.2-CrayGNU-2016.09.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-2.2.2-CrayGNU-2016.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-2.2.2-CrayGNU-2016.11.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-2.2.3-foss-2016.04.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-3.0.0-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-3.0.0-CrayGNU-2016.03.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-3.0.0-CrayGNU-2016.09.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-3.0.0-CrayGNU-2016.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-3.0.0-CrayGNU-2016.11.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-3.0.0-CrayIntel-17.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-3.0.0-CrayIntel-2016.11.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-17.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-18.07.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-18.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-19.03.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-19.06.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-19.09.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-20.06.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayIntel-17.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.2.3-CrayIntel-18.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-19.09.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-19.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-20.06.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-20.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-18.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-19.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-20.06.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-20.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-20.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayPGI-20.08.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-CrayPGI-20.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-cpeGNU-20.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-4.3.4-cpeGNU-20.12.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-5.0.0-cpeGNU-20.10.eb
  easybuild/deprecated_easyconfigs/l/libxc/libxc-5.1.0-cpeGNU-20.10.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.3-CrayGNU-20.11.eb
Labels: enhancement

#2245 [dom] Add singularity 3.7.3-daint on Dom
  easybuild/easyconfigs/s/singularity/singularity-3.7.3-daint.eb
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: enhancement

#2253 [daint-gpu] VASP 6.2.0 OpenACC
  easybuild/deprecated_easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-20.08.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-cuda.makefile.include
  easybuild/deprecated_easyconfigs/v/VASP/VASP-5.4.4-CrayIntel.makefile.include
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08-cuda-pat.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08-pat.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.11.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-cuda.makefile.include
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-CrayIntel.makefile.include
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-cpeGNU-20.10.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-cpeGNU.makefile.include
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-cpeGNU.patch
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-cpeIntel-21.02.eb
  easybuild/deprecated_easyconfigs/v/VASP/VASP-6.1.0-cpeIntel.makefile.include
  easybuild/easyconfigs/n/NCCL/NCCL-2.8.4-CrayPGI-20.11-cuda.eb
  easybuild/easyconfigs/q/QD/QD-2.3.22-CrayPGI-20.11.eb
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-cuda.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-cuda.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayPGI-20.11-acc.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayPGI-acc.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-cpeIntel.makefile.include
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-CrayPGI-20.11.eb
Labels: enhancement

#2259 [daint dom] Add IPCMagic-1.0.1
  easybuild/easyconfigs/i/ipcmagic/ipcmagic-1.0.1-CrayGNU-20.11.eb
Labels: ready_to_be_merged

#2261 [dom daint] Update 7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-mc
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: ready_to_be_merged

#2263 [dom, daint] Add Julia 1.6.0 and bump some extensions
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.0-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.0-CrayGNU-20.11.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner.eb
Labels: ready_to_be_merged

#2264 Update 7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-mc
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: ready_to_be_merged

#2267 [eiger] Fix Amber and NCO with PE 21.03
  easybuild/easyconfigs/a/Amber/Amber-20-15-9-cpeIntel-21.03.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.32-cpeGNU-21.03.eb
  easybuild/easyconfigs/n/NCO/NCO-4.9.8-cpeGNU-21.03.eb
Labels: bugfix

#2268 WIP [eiger] Updated recipes for PE 21.04
  easybuild/easyconfigs/a/Amber/Amber-20-15-9-cpeIntel-21.04.eb
  easybuild/easyconfigs/b/Bison/Bison-3.7.5-cpeGNU-21.04.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-cpeGNU-21.04-python3.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-cpeGNU-21.04.eb
  easybuild/easyconfigs/b/binutils/binutils-2.36.1-cpeGNU-21.04.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-cpeGNU-21.04.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-cpeIntel-21.04.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-cpeGNU-21.04.eb
  easybuild/easyconfigs/c/Charm++/Charm++-6.10.2-cpeIntel-21.04.eb
  easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.2.3-cpeGNU-21.04.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-cpeGNU-21.04.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.3.2-cpeGNU-21.04.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-cpeGNU-21.04.eb
  easybuild/easyconfigs/f/freetype/freetype-2.10.4-cpeGNU-21.04.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.1-cpeGNU-21.04.eb
  easybuild/easyconfigs/g/GREASY/GREASY-19.03-cscs-cpeGNU-21.04.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.5-cpeGNU-21.04.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeAMD-21.04.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeCray-21.04.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeGNU-21.04.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-cpeIntel-21.04.eb
  easybuild/easyconfigs/g/gettext/gettext-0.21-cpeGNU-21.04.eb
  easybuild/easyconfigs/g/graphviz/graphviz-2.46.1-cpeGNU-21.04.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-21.04.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-21.04.eb
  easybuild/easyconfigs/l/LLVM/LLVM-8.0.0-cpeCray-21.04.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.2.0-cpeGNU-21.04.eb
  easybuild/easyconfigs/l/Libint-CP2K/Libint-CP2K-2.6.0-cpeGNU-21.04.eb
  easybuild/easyconfigs/l/libffi/libffi-3.3-cpeGNU-21.04.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.90-cpeGNU-21.04.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.37-cpeGNU-21.04.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-cpeGNU-21.04.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-cpeGNU-21.04.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.1-cpeGNU-21.04.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-cpeGNU-21.04.eb
  easybuild/easyconfigs/m/Mako/Mako-1.1.2-cpeCray-21.04-python3.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.3.3-cpeCray-21.04.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.3.4-cpeGNU-21.04.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeIntel-21.04.eb
  easybuild/easyconfigs/n/NASM/NASM-2.15.05-cpeGNU-21.04.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-cpeGNU-21.04.eb
  easybuild/easyconfigs/n/nodejs/nodejs-14.16.0-cpeGNU-21.04.eb
  easybuild/easyconfigs/o/oidn/oidn-1.2.4-cpeCray-21.04.eb
  easybuild/easyconfigs/o/ospray/ospray-2.4.0-cpeCray-21.04.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-cpeCray-21.04-OSMesa-python3.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-cpeGNU-21.04.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-cpeIntel-21.04.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-cpeIntel-21.04.eb
  easybuild/easyconfigs/v/Vc/Vc-1.4.1-cpeGNU-21.04.eb
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-cpeIntel-21.04.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-cpeGNU-21.04.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-cpeGNU-21.04.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-cpeIntel-21.04.eb
  easybuild/easyconfigs/z/zstd/zstd-1.4.9-cpeGNU-21.04.eb
  jenkins-builds/1.4.0-21.04-eiger
  jenkins-builds/eiger
  jenkins-builds/pilatus
Labels: enhancement

#2270 [dom] Drop xalt when loading julia, since it hijacks libcurl.so and is incompatible
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11.eb
Labels: bugfix

#2201 [daint dom eiger pilatus tsa] Update easyblocks to python 3
  easybuild/easyblocks/boost.py
  easybuild/easyblocks/bzip2cce.py
  easybuild/easyblocks/darshan.py
  easybuild/easyblocks/esmfcray.py
  easybuild/easyblocks/hpcg3.py
  easybuild/easyblocks/idl.py
  easybuild/easyblocks/julia.py
  easybuild/easyblocks/juliabundle.py
  easybuild/easyblocks/juliapackage.py
  easybuild/easyblocks/libqglviewer.py
  easybuild/easyblocks/netcdf4_python.py
  easybuild/easyblocks/netcdf_python.py
  easybuild/easyblocks/openfoamdev.py
  easybuild/easyblocks/pgi.py
  easybuild/easyblocks/pycuda.py
  easybuild/easyblocks/qt.py
  easybuild/easyblocks/rmpi.py
  easybuild/easyblocks/scons.py
  easybuild/easyblocks/xalt.py
Labels: bugfix

#2269 [daint] Update 7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-daint-mc
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: ready_to_be_merged

#2275 [daint dom] Import sys in juliapackage.py
  easybuild/easyblocks/juliapackage.py
Labels: bugfix

#2276 [daint dom] Set JULIA_PKG_SERVER to empty string to disable it
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11.eb
Labels: bugfix

#2277 [dom-gpu] 7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-gpu
Labels: bugfix, ready_to_be_merged

#2278 [daint-gpu] SIRIUS 7.2.1
  easybuild/easyconfigs/g/GSL/GSL-2.6-CrayGNU-20.11.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.2-CrayGNU-20.11.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.2.1-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/s/SPLA/SPLA-1.3.0-CrayGNU-20.11-cuda-mkl.eb
  easybuild/easyconfigs/s/SPLA/SPLA-1.4.0-CrayGNU-20.11-cuda-mkl.eb
Labels: ready_to_be_merged

#2281 [eiger] Create Julia-1.6.0-cpeGNU-21.04.eb
  easybuild/easyblocks/juliapackage.py
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-cpeGNU-21.04.eb
Labels: ready_to_be_merged

#2294 [eiger] QuantumESPRESSO with cpeIntel
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-cpeIntel-21.04.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-cpeIntel-21.04.eb
  jenkins-builds/1.4.0-21.04-eiger
Labels: bugfix

#2296 [eiger] Create JuliaExtensions-1.6.0-cpeGNU-21.04.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.0-cpeGNU-21.04.eb
  jenkins-builds/1.4.0-21.04-eiger
Labels: ready_to_be_merged
