Repository eth-cscs/production, pull requests merged in 2021-06, with the labels that each got.

#2236 [daint dom eiger pilatus] Improved pipeline script for UpdateEB
  jenkins/JenkinsfileUpdateEB
  jenkins/util.groovy
Labels: enhancement, ready_to_be_merged

#2348 [eiger] ddt
  jenkins-builds/1.4.0-21.04-eiger
  jenkins-builds/1.4.0-21.05-pilatus
Labels: ready_to_be_merged

#2257 [dom-gpu] Updated recipes for PE 21.02
  easybuild/easyconfigs/a/Amber/Amber-20-11-7-CrayIntel-21.02-cuda.eb
  easybuild/easyconfigs/b/Bazel/Bazel-3.1.0-CrayGNU-21.02.eb
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/c/CPMD/CPMD-4.3-CrayIntel-21.02-cuda.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.4-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-21.02-APEX-cuda.eb
  easybuild/easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/h/HPX/HPX-1.5.0-CrayGNU-21.02-nonetworking-cuda.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.21.0-CrayGNU-21.02-tf-2.4.0.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-CrayGNU-21.02-python3-serial.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.1-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.0-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.1-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-21.02-batchspawner-cuda.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/m/magma/magma-2.5.4-CrayIntel-21.02-cuda.eb
  easybuild/easyconfigs/m/mdl/mdl-317500.2554-CrayGNU-21.02.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-CrayIntel-21.02-cuda.eb
  easybuild/easyconfigs/o/OptiX/OptiX-6.5.0-CrayGNU-21.02.eb
  easybuild/easyconfigs/o/oidn/oidn-1.1.0-CrayGNU-21.02.eb
  easybuild/easyconfigs/o/ospray/ospray-1.8.5-CrayGNU-21.02.eb
  easybuild/easyconfigs/o/ovito/ovito-3.2.0-CrayGNU-21.02.eb
  easybuild/easyconfigs/p/PCRE/PCRE-8.42-CrayGNU-21.02.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-21.02-EGL-python3.eb
  easybuild/easyconfigs/p/prereq/prereq-tf-2.4-CrayGNU-21.02.eb
  easybuild/easyconfigs/p/pycuda/pycuda-2018.1.1-CrayGNU-21.02-python3-cuda.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-21.02-cuda.eb
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-CrayGNU-21.02-python3.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.1-CrayGNU-21.02-cuda-mkl.eb
  easybuild/easyconfigs/s/spglib/spglib-1.16.0-CrayGNU-21.02.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.0-CrayGNU-21.02.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-21.02-cuda.eb
  easybuild/easyconfigs/v/VTK/VTK-9.0.0-CrayGNU-21.02-EGL-python3.eb
  easybuild/easyconfigs/v/VisRTX/VisRTX-0.1.6-CrayGNU-21.02-cuda.eb
  jenkins-builds/7.0.UP02-21.02-dom-gpu
  login/daint-gpu/.21.02
Labels: enhancement, ready_to_be_merged

#2351 [dom] Sync Dom with Piz Daint
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: bugfix, enhancement

#2354 [dom daint eiger pilatus tsa] Add recipe for ReFrame version 3.6.2
  easybuild/easyconfigs/r/reframe/reframe-3.6.2.eb
Labels: enhancement

#2355 [eiger pilatus] Deploy ReFrame 3.6.2 on eiger/pilatus
  jenkins-builds/1.4.0-21.04-eiger
  jenkins-builds/1.4.0-21.05-pilatus
Labels: ready_to_be_merged

#2357 [eiger pilatus] Fix EB custom modulefile for Lmod
  easybuild/module/EasyBuild-custom/cscs
  easybuild/module/EasyBuild-custom/cscs.lua
Labels: bugfix, enhancement

#2358 [eiger pilatus] EB folders
  easybuild/cpe_external_modules_metadata-21.02.cfg
  easybuild/cpe_external_modules_metadata-21.03.cfg
  easybuild/cpe_external_modules_metadata-21.04.cfg
  easybuild/cpe_external_modules_metadata-21.05.cfg
  easybuild/cpe_external_modules_metadata-21.06.cfg
  easybuild/toolchains/compiler/aocc.py
  easybuild/toolchains/compiler/cpe.py
  easybuild/toolchains/cpeamd.py
  easybuild/toolchains/cpecray.py
  easybuild/toolchains/cpegnu.py
  easybuild/toolchains/cpeintel.py
  easybuild/tools/module_naming_scheme/lowercase_module_naming_scheme.py
  test_naming_scheme/__init__.py
  test_naming_scheme/tools/__init__.py
  test_naming_scheme/tools/__init__.pyo
  test_naming_scheme/tools/module_naming_scheme/__init__.py
  test_naming_scheme/tools/module_naming_scheme/__init__.pyo
  test_naming_scheme/tools/module_naming_scheme/lowercase_module_naming_scheme.pyo
Labels: enhancement

#2352 [eiger] Update spack configs for eiger
  spack/eiger/compilers.yaml
  spack/eiger/packages.yaml
Labels: enhancement

#2361 [eiger] Fix EasyBuild custom modulefile on Eiger
  easybuild/module/EasyBuild-custom/cscs.lua
Labels: bugfix

#2362 [daint dom eiger pilatus tsa] Include custom MNS and toolchains
  easybuild/module/EasyBuild-custom/cscs
  easybuild/module/EasyBuild-custom/cscs.lua
Labels: enhancement

#2363 [daint-gpu dom-gpu] PyTorch-1.9.0-CrayGNU-20.11
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.9.0-CrayGNU-20.11.eb
  jenkins-builds/7.0.UP02-20.11-daint-gpu
  jenkins-builds/7.0.UP02-20.11-dom-gpu
Labels: ready_to_be_merged

#2365 [daint] adding libx264 encoding options
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.4-CrayGNU-20.11.eb
  easybuild/easyconfigs/x/x264/x264-20191217-CrayGNU-20.11.eb
Labels: enhancement

#2366 [eiger] CP2K with MKL
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-cpeIntel-21.04.eb
  easybuild/easyconfigs/c/CP2K/CP2K-8.1-cpeIntel.psmp
Labels: bugfix, enhancement

#2370 [daint-gpu dom-gpu] Add missing ovito for 20.11
  easybuild/easyconfigs/o/ovito/ovito-3.5.2-CrayGNU-20.11.eb
Labels: bugfix

#2372 [eiger pilatus] Fix cscs Lua modulefile to avoid Lmod warning
  easybuild/module/EasyBuild-custom/cscs.lua
Labels: bugfix

#2368 [dom] Add recipe for singularity 3.8.0-daint
  easybuild/easyconfigs/s/singularity/singularity-3.8.0-daint.eb
  jenkins-builds/7.0.UP02-20.11-dom-gpu
  jenkins-builds/7.0.UP02-20.11-dom-mc
Labels: ready_to_be_merged

#2350 WIP [dom-gpu] Updated recipes for PE 21.02
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayCCE-21.02.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayGNU-21.02-python3.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayGNU-21.02.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayIntel-21.02.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-CrayCCE-21.02.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-CrayGNU-21.02.eb
  easybuild/easyconfigs/c/CrayPGI/CrayPGI-21.02.eb
  easybuild/easyconfigs/c/cURL/cURL-7.61.1-CrayGNU-21.02.eb
  easybuild/easyconfigs/c/cftime/cftime-1.0.2.1-CrayGNU-21.02-python3.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.4-CrayGNU-21.02.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-CrayGNU-21.02-python3-serial.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayPGI-21.02.eb
  easybuild/easyconfigs/n/netcdf-python/netcdf-python-1.5.4-CrayGNU-21.02-python3.eb
  easybuild/easyconfigs/o/ogg/ogg-1.3.1-CrayGNU-21.02.eb
  easybuild/easyconfigs/o/ovito/ovito-3.5.2-CrayGNU-21.02.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-CrayGNU-21.02-EGL-python3.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-21.02-cuda.eb
  easybuild/easyconfigs/t/theora/theora-1.2.0alpha1-CrayGNU-21.02.eb
  easybuild/easyconfigs/v/vorbis/vorbis-1.3.3-CrayGNU-21.02.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-CrayCCE-21.02.eb
  jenkins-builds/7.0.UP02-21.02-dom-gpu
Labels: enhancement

#2349 WIP [dom-mc] Updated recipes for PE 21.02
  easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-CrayGNU-21.02-OSMesa-python3.eb
  jenkins-builds/7.0.UP02-21.02-dom-mc
Labels: enhancement

#2376 [eiger pilatus] Deploy Reframe 3.6.3 on eiger/pilatus
  jenkins-builds/1.4.0-21.04-eiger
  jenkins-builds/1.4.0-21.05-pilatus
Labels: ready_to_be_merged
