Repository eth-cscs/production, pull requests merged in 2022-03, with the labels that each got.

#2686 [dom daint tsa] Add recipe for ReFrame version 3.11.0-rc0
  easybuild/easyconfigs/r/reframe/reframe-3.11.0-rc0.eb
Labels: enhancement

#2694 [daint] Fix path error in meta-modules
  login/daint-gpu/21.09
  login/daint-mc/21.09
Labels: bugfix

#2682 [dom] JupyterLab CSCS ipykernel (proof of concept)
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb
Labels: enhancement, ready_to_be_merged, bugfix

#2697 [daint dom] OpenMPI with Cray pmi
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2.eb
Labels: bugfix

#2698 [dom] jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb
Labels: enhancement, ready_to_be_merged

#2700 [daint dom] Update ncview
  easybuild/easyconfigs/n/ncview/ncview-2.1.7-CrayGNU-21.09.eb
Labels: bugfix

#2703 [daint dom] BAGEL with 21.09
  easybuild/easyconfigs/b/BAGEL/BAGEL-1.2.2-CrayGNU-21.09.eb
Labels: enhancement

#2668 [daint-mc] OpenFOAM 5.0
  easybuild/easyconfigs/c/CGAL/CGAL-4.10.2-CrayGNU-21.09.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-CrayGNU-21.09-LABEL_SIZE_64.eb
  easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-5.x-LABEL_SIZE_64
Labels: enhancement

#2705 [daint dom] Minor updates
  easybuild/easyconfigs/b/BAGEL/BAGEL-1.2.2-CrayGNU-21.09.eb
  jenkins-builds/7.0.UP03-21.09-daint-gpu
Labels: bugfix

#2711 [daint-mc] Fix Scotch library dependency
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2112-CrayGNU-21.09.eb
  easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-v2112
Labels: bugfix

#2718 [dom daint tsa] Add recipe for ReFrame version 3.11.0-rc2
  easybuild/easyconfigs/r/reframe/reframe-3.11.0-rc2.eb
Labels: enhancement
