Repository eth-cscs/production, pull requests merged in 2022-09, with the labels that each got.

#2783 [dom daint eiger pilatus tsa] Add recipe for ReFrame CSCS tests version 22.09
  easybuild/easyconfigs/r/reframe-cscs-tests/reframe-cscs-tests-22.09.eb
Labels: enhancement

#2785 [daint] Recipe of CLAPACK
  easybuild/easyconfigs/c/CLAPACK/CLAPACK-3.2.1-CrayGNU-21.09.eb
Labels: enhancement, ready_to_be_merged

#2789 [daint-mc] URL change in tree
  easybuild/easyconfigs/t/tree/tree-1.8.0.eb
Labels: bugfix
