Repository eth-cscs/production, pull requests merged in 2022-10, with the labels that each got.

#2787 [daint-mc] QuantumESPRESSO 7.0 with PLUMED 2.9.0-dev
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.b190b0d-CrayIntel-21.09.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-CrayIntel-21.09-PLUMED-2.9.b190b0d.eb
Labels: enhancement

#2792 [eiger pilatus] Fix system name
  easybuild/module/EasyBuild-custom/cscs
Labels: enhancement, bugfix

#2790 [daint eiger tsa] Add recipe for ReFrame CSCS tests version 22.10
  easybuild/easyconfigs/r/reframe-cscs-tests/reframe-cscs-tests-22.10.eb
Labels: enhancement

#2795 [eiger] Update release of reframe tests
  jenkins-builds/1.4.0-21.12-eiger
Labels: enhancement

#2798 [dom daint eiger pilatus tsa] Add recipe for ReFrame CSCS tests version 22.10.1
  easybuild/easyconfigs/r/reframe-cscs-tests/reframe-cscs-tests-22.10.1.eb
Labels: enhancement

#2799 [eiger pilatus] Update reframe-cscs-tests
  jenkins-builds/1.4.0-21.12-eiger
Labels: enhancement

#2804 [dom daint] XGandalf
  easybuild/easyconfigs/x/XGandalf/XGandalf-b34a34ff02c-CrayGNU-21.09.eb
Labels: enhancement, ready_to_be_merged

#2803 [dom daint] CrystFEL-0.10.1-CrayGNU-21.09
  easybuild/easyconfigs/c/CrystFEL/CrystFEL-0.10.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/x/XGandalf/XGandalf-b34a34ff02c-CrayGNU-21.09.eb
Labels: enhancement, ready_to_be_merged
