Repository eth-cscs/production, pull requests merged in 2022-04, with the labels that each got.

#2723 [dom daint] Add easyconfig for Skopeo 1.7.0
  easybuild/easyconfigs/s/skopeo/skopeo-1.7.0.eb
Labels: ready_to_be_merged

#2725 [daint dom] Update CDO production
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.10-cpeGNU-21.04.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.10-cpeGNU-21.05.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.10-cpeGNU-21.06.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.10-cpeGNU-21.07.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.5-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.5-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.5-CrayGNU-21.02.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.5-CrayGNU-21.09.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.5-CrayIntel-20.08.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.5-CrayIntel-20.11.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.5-CrayIntel-21.02.eb
  easybuild/deprecated_easyconfigs/c/CDO/CDO-1.9.5-CrayIntel-21.09.eb
  jenkins-builds/7.0.UP03-21.09-daint-gpu
  jenkins-builds/7.0.UP03-21.09-daint-mc
Labels: enhancement, clean_up

#2726 [daint-mc] OF5 with OpenMPI
  easybuild/easyconfigs/b/Boost/Boost-1.78.0-CrayGNU-20.08.eb
  easybuild/easyconfigs/c/CGAL/CGAL-4.10.2-CrayGNU-20.08.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-CrayGNU-20.08-LABEL_SIZE_64-OpenMPI.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-CrayGNU-21.09-LABEL_SIZE_64-OpenMPI.eb
  easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-5.x-LABEL_SIZE_64-OpenMPI
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2-CrayGNU-20.08.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2-CrayGNU-21.09.eb
Labels: enhancement

#2730 [daint dom] Update LAMMPS
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-PLUMED-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-cuda-pat.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-pat.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.10-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.10.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-20.08-deepmd-1.2.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-20.11-deepmd-1.2.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-20Sep21-CrayGNU-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-20Sep21-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-20.10-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-20.10.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-20.11-deepmd-2.0.1.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-21.02-cuda.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-21.02.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-20.10.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-21.02.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-21.03.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-21.04.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-21.05.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-21.06.eb
  easybuild/deprecated_easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-21.07.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-24Mar2022-CrayGNU-21.09-cuda.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-24Mar2022-CrayGNU-21.09.eb
Labels: enhancement, clean_up
