Repository eth-cscs/production, pull requests merged in 2022-01, with the labels that each got.

#2589 [dom daint eiger pilatus tsa] Add recipe for ReFrame version 3.9.3
  easybuild/easyconfigs/r/reframe/reframe-3.9.3.eb
Labels: enhancement

#2593 [eiger pilatus] Deploy ReFrame 3.9.3 on eiger/pilatus
  jenkins-builds/1.4.0-21.08-eiger
  jenkins-builds/1.4.0-21.12-eiger
Labels: ready_to_be_merged

#2594 [dom-gpu] CP2K 9.1 (cuda) in production
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-CrayGNU-21.09.eb
  easybuild/easyconfigs/b/Boost/Boost-1.78.0-CrayGNU-21.09-python3.eb
  easybuild/easyconfigs/b/Boost/Boost-1.78.0-CrayGNU-21.09.eb
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09-cuda.eb
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-cuda.psmp
  easybuild/easyconfigs/e/ELPA/ELPA-2021.11.001-CrayGNU-21.09-cuda.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-CrayGNU-21.09.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/l/Libint-CP2K/Libint-CP2K-2.6.0-CrayGNU-21.09.eb
  easybuild/easyconfigs/l/libvori/libvori-210412-CrayGNU-21.09.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.7-CrayGNU-21.09.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-CrayGNU-21.09.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.3-CrayGNU-21.09.eb
  easybuild/easyconfigs/s/SPLA/SPLA-1.5.2-CrayGNU-21.09-cuda-mkl.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.5-CrayGNU-21.09-cuda-mkl.eb
  easybuild/easyconfigs/s/spglib/spglib-1.16.3-CrayGNU-21.09.eb
  jenkins-builds/7.0.UP03-21.09-dom-gpu
Labels: enhancement

#2596 [dom-gpu] QuantumESPRESSO 7.0 (CrayNvidia)
  easybuild/easyconfigs/l/libxc/libxc-5.1.7-CrayNvidia-21.09.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-CrayNvidia-21.09.eb
  jenkins-builds/7.0.UP03-21.09-dom-gpu
Labels: enhancement

#2595 [dom-mc] CP2K 9.1 (multicore) in production
  easybuild/easyconfigs/c/CP2K/CP2K-8.2-CrayGNU.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU.psmp
  easybuild/easyconfigs/e/ELPA/ELPA-2021.11.001-CrayGNU-21.09.eb
  jenkins-builds/7.0.UP03-21.09-dom-gpu
  jenkins-builds/7.0.UP03-21.09-dom-mc
Labels: enhancement

#2597 [dom-mc] QuantumESPRESSO 7.0 Intel
  easybuild/easyconfigs/l/libxc/libxc-5.1.7-CrayIntel-21.09.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-CrayIntel-21.09.eb
  jenkins-builds/7.0.UP03-21.09-dom-mc
Labels: enhancement

#2602 [pilatus] QuantumESPRESSO 7.0 with 21.12
  easybuild/easyconfigs/l/libxc/libxc-5.1.7-cpeIntel-21.12.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-cpeIntel-21.12.eb
  jenkins-builds/1.4.0-21.12-eiger
Labels: enhancement

#2598 [dom-gpu] Create jupyterlab-2.2.10-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-21.09-batchspawner-cuda.eb
Labels: ready_to_be_merged

#2603 [dom-gpu] Update 7.0.UP03-21.09-dom-gpu
  jenkins-builds/7.0.UP03-21.09-dom-gpu
Labels: ready_to_be_merged

#2608 [dom-gpu] Update JupyterLab dependencies
  easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.5.0-CrayGNU-21.09.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/n/nodejs/nodejs-16.13.2-CrayGNU-21.09.eb
  easybuild/easyconfigs/n/nodejs/nodejs-16.13.2.eb
Labels: bugfix

#2610 [dom-gpu] configurable-http-proxy and nodejs deps
  easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.2.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/n/nodejs/nodejs-12.16.1-CrayGNU-21.09.eb
Labels: ready_to_be_merged

#2613 [daint-mc] BAGEL with Cray
  easybuild/easyconfigs/b/BAGEL/BAGEL-1.2.2-CrayGNU-20.11.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-20.11.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.6-CrayGNU-20.11.eb
Labels: enhancement

#2617 [dom] Add easyconfig for fuse-overlayfs/1.8.1
  easybuild/easyconfigs/f/fuse-overlayfs/fuse-overlayfs-1.8.1.eb
Labels: ready_to_be_merged

#2618 [dom] jupyterlab 3.2.8
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb
Labels: enhancement, ready_to_be_merged, bugfix

#2615 [dom-gpu] VASP 6.2.1
  easybuild/easyconfigs/v/VASP/VASP-6.2.1-CrayIntel-21.09-cuda.eb
  easybuild/easyconfigs/v/VASP/VASP-6.2.1-CrayIntel-cuda.makefile.include
  jenkins-builds/7.0.UP03-21.09-dom-gpu
Labels: enhancement

#2619 [dom] Update JupyterLab release in production
  jenkins-builds/7.0.UP03-21.09-dom-gpu
  jenkins-builds/7.0.UP03-21.09-dom-mc
Labels: enhancement

#2621 [dom-gpu] Update GROMACS gpu with 21.09
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-CrayGNU-21.09-cuda.eb
  jenkins-builds/7.0.UP03-21.09-dom-gpu
Labels: enhancement

#2620 [dom-mc] Update GROMACS multicore with 21.09
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-CrayGNU-21.09.eb
  jenkins-builds/7.0.UP03-21.09-dom-mc
Labels: enhancement

#2623 [dom] Update jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb
Labels: ready_to_be_merged, bugfix

#2624 [eiger pilatus] Deploy ReFrame 3.10.0 on eiger/pilatus
  jenkins-builds/1.4.0-21.08-eiger
  jenkins-builds/1.4.0-21.12-eiger
Labels: ready_to_be_merged

#2626 [pilatus] CP2K 9.1 with SIRIUS
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-cpeGNU-21.12.eb
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-cpeGNU.psmp
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-cpeGNU-21.12.eb
  easybuild/easyconfigs/s/SPLA/SPLA-1.5.2-cpeGNU-21.12.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.5-cpeGNU-21.12.eb
Labels: enhancement

#2629 [daint-gpu] VASP 6.3.0
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-21.05-acc.eb
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-acc.makefile.include
Labels: enhancement

#2627 [dom-gpu] CP2K 9.1 with SIRIUS (cuda-mkl)
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09-cuda.eb
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-cuda.psmp
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-CrayGNU-21.09-cuda-mkl.eb
Labels: enhancement

#2628 [dom-mc] CP2K 9.1 with SIRIUS (multicore)
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU.psmp
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-CrayGNU-21.09-mkl.eb
  easybuild/easyconfigs/s/SPLA/SPLA-1.5.2-CrayGNU-21.09-mkl.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.5-CrayGNU-21.09-mkl.eb
Labels: enhancement

#2625 [pilatus] Update Gromacs with CPE 21.12
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-cpeGNU-21.12.eb
  jenkins-builds/1.4.0-21.12-eiger
Labels: enhancement

#2633 [dom-gpu] Fix CP2K cuda with SIRIUS
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-cuda.psmp
Labels: bugfix

#2631 [dom-gpu] VASP 6.3.0 OpenACC
  easybuild/easyconfigs/c/CrayNvidia/CrayNvidia-21.09.eb
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-21.09-acc.eb
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-acc.makefile.include
  jenkins-builds/7.0.UP03-21.09-dom-gpu
Labels: enhancement
