Repository eth-cscs/production, pull requests merged in 2022-02, with the labels that each got.

#2638 [daint-mc] OpenFOAM8
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8.0-CrayGNU-20.11.eb
  easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-8.0-20210316
Labels: enhancement

#2639 [dom-mc] OpenFOAM 8
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8.0-CrayGNU-21.09.eb
Labels: enhancement

#2637 [dom] Update JupyterLab to add nglview for visualization of molecular models
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb
Labels: enhancement, ready_to_be_merged

#2641 [dom-mc] VASP 6.3.0 multicore
  easybuild/easyconfigs/v/VASP/VASP-6.2.1-CrayIntel.makefile.include
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayIntel-21.09.eb
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayIntel.makefile.include
  jenkins-builds/7.0.UP03-21.09-daint-mc
Labels: enhancement

#2642 [pilatus] VASP 6.3.0
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-cpeIntel-21.12.eb
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-cpeIntel.makefile.include
  jenkins-builds/1.4.0-21.12-eiger
Labels: enhancement

#2647 [eiger pilatus] Deploy ReFrame 3.10.1 on eiger/pilatus
  jenkins-builds/1.4.0-21.08-eiger
  jenkins-builds/1.4.0-21.12-eiger
Labels: ready_to_be_merged

#2648 [pilatus] Fix Mesa build
  easybuild/easyconfigs/m/Mesa/Mesa-21.3.2-cpeCray-21.12.eb
Labels: bugfix

#2650 [dom-gpu] Update VASP default
  jenkins-builds/7.0.UP03-21.09-daint-gpu
Labels: enhancement

#2651 [daint-mc] OpenFOAM v2112
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2112-CrayGNU-20.11.eb
  easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-v2112
Labels: enhancement

#2655 [dom] Small update to jupyterlab 3.2.8 module
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb
Labels: ready_to_be_merged, bugfix

#2658 [dom] jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb
Labels: ready_to_be_merged

#2656 [dom-mc] OpenFOAM v2112
  easybuild/easyconfigs/c/CGAL/CGAL-5.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2112-CrayGNU-21.09.eb
Labels: enhancement

#2667 [eiger] Update software stack
  jenkins-builds/dismissed/1.4.0-21.08-eiger
  jenkins-builds/dismissed/1.4.0-21.09-eiger
  jenkins-builds/dismissed/1.4.0-21.09-pilatus
  jenkins-builds/dismissed/1.4.0-21.10-eiger
  jenkins-builds/dismissed/1.4.0-21.10-pilatus
  jenkins-builds/eiger
Labels: enhancement

#2674 [daint-gpu] OpenMPI 4.1.2
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2.eb
Labels: enhancement

#2679 [daint dom] Link MPI-only ELPA with CP2K
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-cuda.psmp
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU.psmp
Labels: bugfix

#2684 [dom,daint] Bring back spack-config/1.5
  easybuild/easyconfigs/s/spack-config/spack-config-1.5-cdt-21.09.eb
  easybuild/easyconfigs/s/spack-config/spack-config-1.5-cdt-cuda-21.09.eb
Labels: bugfix

#2678 [daint] GDAL-3.4.1-CrayGNU-21.09 with depenencies
  easybuild/easyconfigs/e/expat/expat-2.2.10-CrayGNU-21.09.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.4.1-CrayGNU-21.09-python3.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.10.2-CrayGNU-21.09-python3.eb
  easybuild/easyconfigs/h/HDF/HDF-4.2.15-CrayGNU-21.09.eb
  easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.7.0-CrayGNU-21.09.eb
Labels: enhancement

#2688 [daint dom] Update PLUMED
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-20.08-mpi.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-20.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.6.1-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.6.1-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.6.1-CrayIntel-20.08.eb
  easybuild/deprecated_easyconfigs/p/PLUMED/PLUMED-2.7.1-CrayGNU-20.11.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.0-CrayGNU-21.09.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.0-CrayIntel-21.09.eb
  easybuild/easyconfigs/p/PLUMED/plumed-compiler.patch
  jenkins-builds/7.0.UP03-21.09-daint-gpu
  jenkins-builds/7.0.UP03-21.09-daint-mc
Labels: enhancement, clean_up

#2689 [daint-mc] QuantumESPRESSO 6.3 with PLUMED
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-CrayIntel-20.08-pat.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-CrayIntel-20.08.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-20.08-cuda-pat.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-CrayIntel-20.08-pat.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-CrayIntel-20.08.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-21.02-cuda.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-CrayIntel-20.11.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-CrayIntel-21.02.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-cpeIntel-21.04.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-cpeIntel-21.05.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-cpeIntel-21.06.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-cpeIntel-21.07.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.8.0-CrayIntel-20.11.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.8.0-CrayNvidia-21.05.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.8.0-cpeIntel-21.07.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayGNU-20.08-cuda-pat.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayGNU-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayGNU-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc6-CrayGNU-20.08-cuda.eb
  easybuild/easyconfigs/c/CrayIntel/CrayIntel-21.09-19.eb
  easybuild/easyconfigs/g/GSL/GSL-2.7-CrayIntel-21.09-19.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.0-CrayIntel-21.09-19.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-CrayIntel-21.09-19-PLUMED-2.8.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-CrayIntel-21.09-19.eb
Labels: enhancement, clean_up

#2690 [daint dom] ELPA fix for CP2K and SIRIUS
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.11-cuda-pat.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.11-pat.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-21.02-cuda.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-21.02.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-cuda.psmp
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-CrayGNU.psmp
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-cpeGNU-20.10.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-7.1-cpeGNU.psmp
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11-cuda-pat.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11-pat.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-21.02-cuda.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-21.02.eb
  easybuild/deprecated_easyconfigs/c/CP2K/CP2K-8.2.69b8c2e-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.08.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-21.02-cuda.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-21.02.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-20.08.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2019.11.001-cpeGNU-21.08.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-21.02-cuda.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-21.02.eb
  easybuild/deprecated_easyconfigs/e/ELPA/ELPA-2021.05.002-CrayGNU-20.11.eb
  easybuild/deprecated_easyconfigs/s/SIRIUS/SIRIUS-6.5.3-CrayIntel-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-20.08-cuda-pat.eb
  easybuild/deprecated_easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-21.02-cuda.eb
  easybuild/deprecated_easyconfigs/s/SIRIUS/SIRIUS-7.0.2-CrayGNU-20.08-cuda.eb
  easybuild/deprecated_easyconfigs/s/SIRIUS/SIRIUS-7.2.1-CrayGNU-20.11-cuda.eb
  easybuild/deprecated_easyconfigs/s/SIRIUS/SIRIUS-7.2.3-CrayGNU-20.11-cuda.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.11.002-CrayGNU-21.09-cuda.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.11.002-CrayGNU-21.09.eb
Labels: bugfix, clean_up

#2692 [daint-mc] CP2K and SIRIUS with latest ELPA
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-CrayGNU-21.09-mkl.eb
Labels: bugfix

#2691 [daint-gpu] CP2K and SIRIUS with latest ELPA
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09-cuda.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-CrayGNU-21.09-cuda-mkl.eb
Labels: bugfix

#2693 [daint] Prepare switch of login meta-modules
  login/daint-gpu/.20.11
  login/daint-gpu/.version
  login/daint-gpu/21.09
  login/daint-mc/.version
  login/daint-mc/20.11
  login/daint-mc/21.09
Labels: enhancement
