Repository eth-cscs/production, pull requests merged in 2024-03, with the labels that each got.

#2961 [eiger pilatus] Lua modulefile for EasyBuild-custom
  easybuild/module/EasyBuild-custom/cscs.lua
Labels: bugfix

#2967 [eiger pilatus] Update JenkinsfileTestingEB to disable Lmod cache
  jenkins/JenkinsfileTestingEB
Labels: bugfix

#2968 [eiger] Update TestingEB
  jenkins/JenkinsfileTestingEB
Labels: bugfix

#2969 [eiger] Fix missing newline in buildlist
  jenkins/JenkinsfileTestingEB
Labels: bugfix

#2970 [eiger] Remove empty line
  jenkins/JenkinsfileTestingEB
Labels: bugfix

#2966 [eiger] Update JenkinsfileUpdateEB, EasyBuild-custom Lua modulefile and selected recipes
  easybuild/cpe_external_modules_metadata-22.05.cfg
  easybuild/cray_external_modules_metadata-22.09.cfg
  easybuild/easyconfigs/b/binutils/binutils-2.37-cpeGNU-21.12.eb
  easybuild/easyconfigs/c/CDO/CDO-1.9.10-cpeGNU-21.12.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-22.05.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.11.001-cpeGNU-21.12.eb
  easybuild/easyconfigs/g/graphviz/graphviz-2.46.1-cpeGNU-21.12.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-20Sep21-cpeGNU-21.12.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeGNU-21.12.eb
  easybuild/easyconfigs/n/NCL/NCL-6.6.2.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-cpeGNU-21.12.eb
  easybuild/easyconfigs/s/SPLA/SPLA-1.5.2-cpeGNU-21.12.eb
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-cpeIntel-21.12.eb
  easybuild/easyconfigs/v/Visit/Visit-3.3.1-cpeGNU-21.12.eb
  easybuild/easyconfigs/x/x265/x265-3.2.1-cpeGNU-21.12.eb
  easybuild/module/EasyBuild-custom/cscs.lua
  jenkins/JenkinsfileUpdateEB
Labels: enhancement

#2973 [daint dom eiger pilatus] Files for CPE 23.05
  easybuild/cpe_external_modules_metadata-23.05.cfg
  jenkins-builds/21.12-pilatus
  jenkins-builds/production.sh
Labels: enhancement

#2975 [pilatus] Update metadata and custom modulefile for CPE 23.09
  easybuild/cpe_external_modules_metadata-23.09.cfg
  easybuild/module/EasyBuild-custom/cscs
  easybuild/module/EasyBuild-custom/cscs.lua
Labels: enhancement

#2976 [eiger] Fix recipes for next update
  easybuild/easyconfigs/c/Charm++/Charm++-6.10.2-cpeGNU-21.12.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-5.0-cpeGNU-21.12.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-5.0-cpeGNU.patch
  easybuild/easyconfigs/j/jupyter-utils/jupyter-utils-0.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-20Sep21-cpeGNU-21.12.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeGNU-21.12.eb
  easybuild/easyconfigs/v/VASP/VASP-6.3.0-cpeIntel.makefile.include
  jenkins-builds/21.12-pilatus
  jenkins/JenkinsfileUpdateEB
Labels: enhancement, bugfix

#2977 [eiger] Fix module load hub
  easybuild/easyconfigs/g/GREASY/GREASY-19.03-cscs-cpeGNU-21.12.eb
  jenkins/JenkinsfileUpdateEB
Labels: bugfix

#2979 [pilatus] Add missing cpeGNU-23.09.eb
  easybuild/easyconfigs/c/cpeGNU/cpeGNU-23.09.eb
Labels: bugfix

#2981 [daint dom] Add pytorch 2.2.1 to production list
  jenkins-builds/7.0.UP03-21.09-daint-gpu
Labels: enhancement
