Repository eth-cscs/production, pull requests merged in 2024-07, with the labels that each got.

#3019 [dom daint eiger pilatus tsa] Add recipe for ReFrame CSCS tests version 24.07
  easybuild/easyconfigs/r/reframe-cscs-tests/reframe-cscs-tests-24.07.eb
Labels: enhancement

#3020 [eiger pilatus] Update builds on Eiger
  easybuild/easyconfigs/r/reframe-cscs-tests/reframe-cscs-tests-24.07.eb
  jenkins-builds/23.12-eiger
  jenkins-builds/23.12-pilatus
  jenkins-builds/dismissed/21.12-eiger
  jenkins-builds/eiger
  jenkins/Machines.groovy
Labels: enhancement

#3021 [eiger] Update external metadata on Eiger
  easybuild/module/EasyBuild-custom/cscs
  easybuild/module/EasyBuild-custom/cscs.lua
Labels: bugfix

#3024 [pilatus eiger] Update jupyterlab with CPE 23.12
  easybuild/easyconfigs/j/jupyterlab/jupyterlab-4.2.3-cpeGNU-23.12.eb
Labels: enhancement, ready_to_be_merged

#3026 [eiger pilatus] Update 23.12-eiger
  jenkins-builds/23.12-eiger
Labels: bugfix

#3028 [daint-gpu dom-gpu] GROMACS 2024 with CUDA
  easybuild/easyconfigs/g/GROMACS/GROMACS-2024-CrayGNU-21.09-cuda.eb
Labels: enhancement

#3025 [dom daint eiger pilatus tsa] Add recipe for ReFrame version 4.7.0-dev.2
  easybuild/easyconfigs/r/reframe/reframe-4.7.0-dev.2.eb
Labels: enhancement
